
# BEST PRACTICES FOR IMPLEMENTING A MANAGEMENT PROCEDURE APPROACH {#sec:approach-best-practices}

## STEP 1: DEFINE THE DECISION CONTEXT {#sec:approach1}

Key questions to guide defining the decision context for MSE include:

* What is the exact decision to be made?

* What is the time frame for making the decision?

* What are specific roles and responsibilities of parties involved? Parties include Science, Management, First Nations, industry, academia, and/or non-governmental organizations (NGOs).

* How will the final decision be made?

For this rebuilding plan, the decision to be made is which MP to use to determine catch limits for the period until the next available catch advice.
The time-frame for making the decision should be stated in the request for science advice.

The final decision on which MP to use to determine catch limits should be made based on a consensus by the Regional Peer Review (RPR) committee, after review of the scientific content of the advice (including the structure and content of the OMs), and consideration of the relative performance of the MPs with respect to meeting stated objectives and trade-offs among performance metrics.
