# INTRODUCTION

## BACKGROUND

*TODO: edit this - Midoli has taken a first crack at this*


The purpose of this project is to provide scientific advice to support revision of the rebuilding plan for the Inside Population of Yelloweye Rockfish (*Sebastes ruberrimus*), consistent with national policy guidance [@DFO2009; @DFO2013]. The project applies a closed-loop simulation approach to test and identify management procedures that meet rebuilding objectives for the Inside population of Yelloweye Rockfish (4B groundfish management area). The project has three parts:
1. Review and revise rebuilding objectives.
2. Development of one or more operating models to represent alternative hypotheses for stock and fishery dynamics and to simulate future data.
3. Evaluation of the performance of candidate management procedures with respect to meeting the rebuilding objectives and characterisation of trade-offs associated with alternative rebuilding plans.

## MOTIVATION

*TODO edit - Midoli has taken a first crack at this*

Canadian fish stocks that have been assessed as being below the Limit Reference Point (LRP), i.e., in the Critical Zone [@DFO2009], require a rebuilding plan to rebuild the stock out of the Critical Zone.  Fisheries and Ocean's Canada's (DFO's) guidance document for the development of rebuilding plans [@DFO2013] states that rebuilding plans should include short- and long-term objectives, where short-term objectives should be achieved within the life of the rebuilding plan and are characterised by:

1. a target.
2. desired time to reach the target.
3. acceptable probability of reaching the target.

Rebuilding plans should also include planned management measures, milestone objectives and should undergo regular (no more than three years) performance reviews, in addition to annual monitoring and evaluation. Current guidance states that the timelines (TODO fix this) should be 1.5 to 2 times the generation time of the species [@DFO2013].

### Legislative obligations

On June 21, 2019, major amendments to Canada's [*Fisheries Act*](https://laws-lois.justice.gc.ca/eng/acts/f-14/page-3.html#h-1175547) received Royal Assent, thus passing them into Canadian law. Among many other amendments, provisions in the new *Fisheries Act* require that fish stocks be managed at sustainable levels, specifically at biomass levels above the LRP. Hereafter referred to as the "Fish Stocks provisions", the provisions legislate elements of Canada's Sustainable Fisheries Framework (SFF) and Precautionary Approach (PA) Framework, and state:

> **Measures to maintain fish stocks**
> 6.1(1) In the management of fisheries, the Minister shall implement measures to maintain major fish stocks at or above the level necessary to promote the sustainability of the stock, taking into account the biology of the fish and the environmental conditions affecting the stock.

> **Limit reference point**
> 6.1 (2) If the Minister is of the opinion that it is not feasible or appropriate, for cultural reasons or because of adverse socio-economic impacts, to implement the measures referred to in subsection (1), the Minister shall set a limit reference point and implement measures to maintain the fish stock above that point, taking into account the biology of the fish and the environmental conditions affecting the stock.

> **Plan to rebuild**
> 6.2(1) If a major fish stock has declined to or below its limit reference point, the Minister shall develop a plan to rebuild the stock above that point in the affected area, taking into account the biology of the fish and the environmental conditions affecting the stock, and implement it within the period provided for in the plan.

For data-limited stocks, data are generally insufficient to adequately account for uncertainty in development of biological reference points (BRPs) and assessment of stock status relative to BRPs. To comply with the legal requirements identified in the Fish Stocks provisions for data-limited species, it is therefore necessary to develop defensible methods and a framework for setting catch limits that promote sustainability and maintain stocks above their LRP, recognizing that, in many cases, the LRP and stock status cannot be reliably estimated.

Inside Yelloweye Rockfish is a data-limited species targeted in hook and line commercial fisheries, Food Social and Ceremonial (FSC) fisheries, and recreational fisheries. The population was assessed in 2011 as being below the LRP [@Yamanaka2011; @DFO2012] and a rebuilding plan was developed and published in Appendix 9 of the Pacific Region Integrated Fishery Management Plan (IFMP) for Groundfish [@DFO2018]. The current rebuilding plan has the objective to "rebuild the stock above the LRP over 80 years with 56% probability of success". The milestone objectives are to "achieve positive trends within each 10 year period". The management measure in the current rebuilding plan is to keep the total annual catch (commercial, recreational, FSC, and survey) below 15 tonnes (see [@DFO2018], App. 9 for details).

According to the Rebuilding Plan guidance document, rebuilding plans must be reviewed every three years. Science received a Request for Science Information and Advice (RSIA) from the Pacific Groundfish Management Unit that states: "Science support is requested to review rebuilding plan objectives, and if indicated by the review, adjust the rebuilding plan objectives so that they can be monitored and evaluated, and  are consistent with the Rebuilding Plan guidance document." Review of the rebuilding plan objectives includes reviewing whether the current stated probability of rebuilding (56%) is consistent with the guidance document [@DFO2013], which states that there should be a high probability of rebuilding the stock within the stated time-frame.

The guidance document [@DFO2013] identifies some recommended management measures, which include keeping removals from all sources to the lowest possible level; development of a harvest control rule (HCR); and application of management strategy evaluation (MSE) to examine the consequences of alternative management measures aimed at rebuilding the stock. The current rebuilding plan implements an annual fixed TAC, which has not been simulation-tested.

Inside Yelloweye Rockfish, which reside in area 4B (Strait of Georgia, Johnstone Strait, and Queen Charlotte Strait), are genetically distinct from the outside population of Yelloweye Rockfish whose range covers the rest of the coast [@Andrews2018; @Siegle2011; @Siegle2013] and are considered two separate designatable units by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC) [@COSEWIC2008].
The northerly boundary between the two genetic populations is found in the middle of the Queen Charlotte Strait, north of Malcolm Island.
Our understanding of the Southern boundary has recently changed based on analyses presented in Andrews et al. (2018) who argue that the Victoria Sill is the most likely geological boundary between the two populations.
The two populations are assessed and managed independently using the Groundfish Management Area 4B to define the inside stock despite the fact that 4B extends past the boundaries of the biological population (**Figure x**).

Yelloweye are a long-lived species and have been aged up to 121 years in B.C. although the maximum age for inside Yelloweye is 98 years [@Kepple2019]. They prefer rocky demersal habitats that have a patchy, discontinuous distribution along the inner coast [@Yamanaka2011]. These life history traits make Inside Yelloweye vulnerable to overexploitation by fisheries. Inside Yelloweye Rockfish are listed under the Species at Risk Act (SARA) as a Species of Special Concern [@COSEWIC2008], and is anticipated to be reassessed by the COSEWIC in 2020. Project results may inform a COSEWIC reassessment and will inform a SARA Recovery Potential Assessment for the Inside Population, should one be required.
