# METHODS


## DATA

Data are described in Appendices 

*TODO: Not sure of the best place for the data section*

*TODO: Edit all of this text. Placeholder for now. RF can do this*

We follow the methods recommended in the Management Procedure Framework for Groundfish in British Columbia [@anderson2020]. The framework follows six best practice steps described below. For more details on the best practice steps see @anderson2020 <!--should this say "in press"?-->.

@punt2016 reviewed best practices for MSE and identified five key steps in the process (Steps 2--6 below). In large part, the DLMtool software has been designed to allow practitioners to follow these steps [Figure \@ref(fig:mse-chart); @carruthers2018]. We also identify a critical first step (Step 1 below): defining the decision context [@gregory2012 and Cox and Benson (unpublished)].

*TODO: Mention this is done in a simulation framework. Very briefly introduce dlmtool and msetool here*

  Step 1: define the decision context

  Step 2: selection of objectives and performance metrics 

  Step 3: selection of uncertainties/specification of operating models 

  Step 4: identification of candidate management procedures 

  Step 5: simulation of the application of the management procedures 

  Step 6: presentation of results and selection of management procedure

*TODO: possibly add Step 7 ... monitoring future surveys and triggering review of OM if surveys are outside projection envelope"

## BEST PRACTICES FOR IMPLEMENTING A MANAGEMENT PROCEDURE APPROACH 

### STEP 1: DEFINE THE DECISION CONTEXT {#sec:approach1}

The decision to be made is which MP to use to determine catch limits for the period until the next available catch advice. The time-frame for making the decision should be stated in the request for science advice.

The boundaries on the project ...

The final decision on which MP to use to determine catch limits should be made based on a consensus by the Regional Peer Review (RPR) committee, after review of the scientific content of the advice (including the structure and content of the OMs), and consideration of the relative performance of the MPs with respect to meeting stated objectives and trade-offs among performance metrics. 

### STEP 2: SELECTION OF OBJECTIVES AND PERFORMANCE METRICS  {#sec:approach2}

Here we describe a set of provisional objectives and associated performance metrics. In real applications of the framework, objectives should be refined on a stock-by-stock basis, with advice from Fisheries Management, First Nations, commercial and recreational fishing representatives, NGOs and other affected parties. Other objectives could be added (e.g., cultural objectives), decided on a stock-by-stock basis.

Key provisional conservation objectives are guided by the PA Framework [@dfo2006; @dfo2009] and rebuilding plan guidance [@DFO2013], elements of which are incorporated into the Fish Stocks provisions of the *Fisheries Act* (see Section \@ref(motivation)). Additional objectives related to fisheries yield and variability in annual fisheries yield are based on precedents in other DFO Pacific Region analyses [e.g., @cox2008a; @forrest2018; @cox2019].

*TODO: LIST THE REBUILDING PLAN OBJECTIVES. How have these changed compared to the original objectives and why? - MJB first crack*

The rebuilding plan objectives for Inside Yelloweye were published in Appendix 9 of the Pacfic Region Integrated Fishery Management Plan (IFMP) for Groundfish in 2018 [@DFO2018]. The original rebuilding plan objectives were:
*"Rebuild the stock above the LRP over 80 years with 56% probability of success".
*"Achieve positive trends within each 10 year period"
The management procedure that was agreed upon to meet these objectives was to keep the the combined TAC (commercial, recreational, FSC) below 15 tonnes annually [@DFO2018]. 

For this analysis, a set of refined objectives were proposed for Inside Yelloweye in order to be consistent with legislated requirements under the new *Fisheries Act*, specify the length of the projection period to be used for simulations, and to account for other processes, including the anticipated re-assessment by COSEWIC. The new objectives are:

1. Rebuild the stock above the LRP over 56 years (1.5 generations) with at least 95% probability of success
2. Achieve positive trends in biomass within each 10 year period or if the stock is above the LRP" <!--I think this one is not correctly worded, I took it from Quang's presentation but I'm not sure where to find the proper one (MJB)-->

*TODO: Also list COSEWIC indicators- MJB first crack*
COSEWIC and DFO have different criteria for assessing the status of marine fish stocks. DFO focuses on current status relative to some reference state or threshold, while COSEWIC criteria (based on IUCN Red List categories) are more focused on the probability of decline over past generations and the probability of continued declines in the future e.g. Criteria A1,2,3,or 4 in [@COSEWIC2015]. In order for this analysis to inform the COSEWIC re-assessment, we report the probability that the stock has declined at least 30%, 50%, and 70% over the past 3 generations. <!--Not sure how the whole discussion around extinction risk (COSEWIC indicator E) came out. From the emails I read this quantitative metric is rarely used by COSEWIC for marine fishes (MJB) -->

*TODO: List the performance metrics - MJB first crack*
We propose the following performance metrics, where MSY refers to maximum sustainable yield, *B*~MSY~ refers to equilibrium spawning biomass at MSY, and *F*~MSY~ refers to the fishing mortality that produces MSY over the long term:
<!--from the powerpoint slides from Quang (MJB)-->

  * LRP 1.5 GT		P[B > 0.4 BMSY] after 1.5 GT (56 years) Satisficing: only consider MPs with 95% probability
  * LRP 1GT		    P[SSB > LRP] after 1 GT (38 years) 		
  * USR 1.5 GT		P[SSB > USR] after 56 years
  		
  * ST C10		P[Catch > 10 t] during 2020-2029
  * ST C15    P[Catch > 15 t] during 2020-2029
  * LT C20		P[Catch > 20 t] during 2020-2029
  * LT C20		P[Catch > 20 t] after 1 Generation time
  * AAVC			Probability of < 20% inter-annual variability in catch

Performance metrics are averaged across reference set of OMs or reported individually.

*TODO: RF Moved these from MP section but not sure if they are needed. Go through all these and delete if they were not used or explain why they are here ... or add them to results if they are needed *

## Historical metrics 

### COSEWIC Metric A

P70 - Probability that population decline hasn't exceeded 70% over 3 generations
where generation time = 38 years for inside yelloweye

P[1 - B_2019/B_1918 < 0.7]

P50 - Probability that population decline hasn't exceeded 50% over 3 generations 

P[1 - B_2019/B_1918 < 0.5]

P30 - Probability that population decline hasn't exceeded 30% over 3 generations

P[1 - B_2019/B_1918 < 0.3]


### Reference points

USR - Probability that B_2019 > 0.8 BMSY
LRP - Probability that B_2019 > 0.4 BMSY

*TODO: RF moved these from Step 6. Probably not needed*

## Performance metrics of MPs

<!-- Use AADC instead of AAVY -->
AADC - average absolute deviation in catch over $n$ years is defined as: <!-- See gfmp -->
$AADC = \dfrac{1}{n-1}sum_{y=2}^n \mid C_y - C_{y-1} \mid$
`ST AADC` - probability that AADC in the first decade of the projection period is less than that in 2012 - 2019 (since start of 15 t TAC)

### Extinction Risk - COSEWIC E
We propose two potential thresholds of 2% B_0 and 5% B_0 to quantititively calculate risk for future extinction. 
Using a projection period of 100 years, we calculate the probability that the stock remains above 2% and 5% B0:

`2% B_0` = P[B_y > 0.02 B_0]
`5% B_0` = P[B_y > 0.05 B_0]


### STEP 3: SELECTION OF UNCERTAINTIES/SPECIFICATION OF OPERATING MODELS {#sec:approach3}

DLMtool OMs are organized into four main components representing a real fished system:

1. population dynamics of the fish stock (e.g., growth, recruitment, mortality);
2. fishery dynamics (e.g., selectivity, spatial targeting);
3. observation processes (e.g., bias and precision in survey indices); and
4. management implementation (e.g., percentage overages of catch limits).

DLMtool's companion software package, MSEtool [@huynh_msetool_2019], includes an extremely efficient implementation of a stock reduction analysis (SRA) [@kimura1982; @walters2006], which is effectively a catch-at-age model that estimates the combinations of historical fishing mortality and recruitment that would be consistent with the observed data. The SRA model is used to condition the following OM parameters: <!--not sure these are the correct ones below -->

* unfished recruitment
* depletion
* relative fishing effort
* annual recruitment deviations
* selectivity parameters (if age or length composition data are included as inputs to the SRA)

Best practice recommends calibrating or conditioning OMs with observed data so they can reproduce historical observations. Statistical diagnostics or retrospective analyses can then be used to generate a suitable set of OMs. This is also known as conditioning the OMs. The OMs were conditioned using catch, survey indices, and age-composition data from the inside Hard Bottom Longline (HBLL) survey. 




*from Quang*
General settings:
- Max age = 80 years (plus group accumulator age)
- Use SRA model (cite gfmp)
- Each replicate fits a different value of M and h (sampled independently)
- Fix selectivity of fisheries to values from outside YE. Use hook and line for commercial (there is little to no trawl fishery for inside pop)
- Estimate rec devs after 1950 (age comps only available after 2003)
- Estimate HBLL selectivity. Mirror the dogfish selectivity in each replicate to match that for HBLL
- Multinomial annual sample size for age comps based on the number of sampling trips.

- Initial fit did not fit dogfish survey well. Retrospective analysis showed bias in SSB (For model with M and h set to mean priors, rho = 0.25 for 11 years when removing up to 11 years of data). 11 years of data were used primarily to evaluate consistency of the model going back to 2009 which was the terminal year for the 2011 assessment.
- Subsequent that increased likelihood weight (lambda = 4) to dogfish survey also removed retrospective bias (SSB rho = -0.05). However, HBLL age of full selectivity was estimated to be 40+ years, which is inconsistent with the age comps. This is though to be unlikely, since the modes of the HBLL age compars around 20 years, which was what was estimated in the initial fit in previous paragraph, and is also the estimated full selectivity for the HL gear in the outside population.  
- Next, it was decided to fix the HBLL selectivity to that from the initial fit while also upweighting the dogfish survey. This fit generated small retrospective bias (SSB rho = -0.07) for the fit with M and h mean priors.
- Retrospective bias among these fits vary depending on the assumption of M, with larger bias at higher M. This is another uncertainty associated with the OM conditioning process.
<!-- I will generate a plot of SSB rho vs. M to show this -->

To isolate the effects of specific sources of uncertainty on performance of MPs, alternative OMs were developed that changed the value (or distribution) of one parameter or data source of interest. OMs are divided into a reference set of core OMs representing the most important plausible model uncertainties, and a robustness set for testing sensitivity to a broader range of structural uncertainties [@rademeyer2007].

#### Reference set

From the initial fit, the following OMs were developed as the reference set:

1. Upweight dogfish survey: Uses the initial fit but upweight dogfish selectivity and fix HBLL full selectivity age to 20 years.
Additional things to mention:
- Projection period of 100 years to facilitate extinction risk for COSEWIC assessment.
- Future recruitment deviations sampled in logspace with SD = 0.4 and autocorrelation = 0.8, the latter estimated post-hoc from the SRA model.
- Only the HBLL index is assumed to be available for the MPs. Observed values generated with SD = 0.25 in logspace.

2. Low catch - to address uncertainty in historical catch, an alternative scenario was used where the 1986-2005 commercial catch was not doubled, and instead the gfdatabase records of commerical catch were used. Compared to (1), this OM implies a relatively smaller stock that has been fished more heavily. Between 1 and 2, relatively large extremes in assumed catches are used to illustrate the effect of catch uncertainty. 

3. Episodic recruitment - to address uncertainty in future productivity, an alternative scenario where recruitment is more variable. Rockfish assessments in the Pacific have estimated occasional extreme year classes (examples? POP, boccacio?). SRA may not estimate large cohorts, this could be a limitation of the available data to detect large cohorts. From (1), extreme recruitment is generated on average once every generation (38 years). If y is an extreme recruitment year, then the recruitment is sampled with lognormal with SD = 2.

<!-- I need to add an equation to describe episodic recruitment -->

4. Estimate HBLL selectivity - same as 1 but HBLL selectivity is allowed to be estimated to address conditioning uncertainty.

#### Robustness set

Two robustness OM were considered:

(A) Low M - Same as (1), but M ~ Lognormal(0.025, 0.2), pessimistic scenario for stock productivity and rebuilding

(B) Higher CV HBLL - Future HBLL index is less precise than in (1). Instead of SD = 0.25, we use the SD and autocorrelation from the index residuals in OM (1). In doing so, this scenario evaluate MPs if we've overestimated the precision of the HBLL survey and conditioning uncertainty (we've generated larger than expected residuals).


*TODO. Decide if we will have our own SRA appendix or refer to MP Framework*

Further details on the SRA OM-calibration model are available in Appendix \@ref(app:sra).

### STEP 4: IDENTIFICATION OF CANDIDATE MANAGEMENT PROCEDURES  {#sec:approach4}

@anderson2020 screened all MPs available in DLMtool as of November 2019 along with recent MPs used in BC groundfish reports. DLMtool includes MPs that make different types of management recommendations.
These recommendations include adjustments to total allowable catch (TAC), effort, or spatial allocation of catch or effort.
For Inside YE, we focus on MPs that make TAC recommendations because the stock is managed by quotas.

We focus on two main types of MPs: data-based and model-based MPs.

All MPs included in this framework are fully described in Appendix \@ref(app:MPs).

## Reference MPs
<!-- Only No fishing (NFref), FMSY75 and FMSY -->

*TODO: move MPs into appendix*

## Fixed TAC MPs

- Look at different values of fixed catch, including 5, 10, and 15 t. 15 t can be considered the status quo.

## Index-based MPs

Index-based MPs set the TAC relative to the change in the index over time. Slope-based MPs increase or decrease the TAC in accordance with the estimated slope in the index over recent time, while ratio MPs increase or decrease the TAC in accordance with the ratio of the index from two different time periods.

A third type, target MPs, adjusts the TAC based on the ratio of the recent index and a target index value. These were not considered here as further guidance from management would be needed in order to select the appropriate target value. For the rebuilding plan, the goal is to ensure that the stock is above the LRP, however, the LRP is not likely to be the target state of nature that would be suitable for management and stakeholders.

Evaluate index MPs with either annual or 5-year updates. For the latter, fixed TAC between updates.

All index-based MPs set a minimum TAC = 0.5 t for surveys.

### Index slope

$\text{TAC}_y = C_{y-1} (1 + \lambda I^{\text{slope}}_{y-1})$

<!-- Geromont, H.F. and Butterworth, D.S. 2014. Complex assessment or simple management procedures for efficient fisheries management: a comparative study. ICES J. Mar. Sci. doi:10.1093/icesjms/fsu017 -->

Various tuning parameters can alter performance of MPs:
Lambda controls the change in TAC relative to change in slope.
I_slope can vary by the number of years in which the slope is calculated.
Two types of index slope MPs:

GB_slope - use above eq but ensure that $0.8 C_{y-1} \le TAC_y \le 1.2 C_{y-1}$.

Three configurations to explore:
GB_slope_lambda1   $\lambda = 1$	  $I^{slope}_{y-1}$ is calculated from index in the preceding 5 years
GB_slope_lambda05  $\lambda = 0.5$	$I^{slope}_{y-1}$ is calculated from the preceding 5 years
GB_slope_yrs10     $\lambda = 1$	  $I^{slope}_{y-1}$ is calculated from the preceding 10 years


Islope - no cap. Thus smaller values of $\lambda$ may be prudent.

Islope_5_lambda04  $\lambda = 0.4$	  $I^{slope}_{y-1}$ is calculated from index in the preceding 5 years
Islope_10_lambda04 $\lambda = 0.4$	$I^{slope}_{y-1}$ is calculated from the preceding 10 years
Islope_10_lambda08 $\lambda = 0.8$	  $I^{slope}_{y-1}$ is calculated from the preceding 10 years


### Index ratio

$\text{TAC}_y = C_{y-1} \dfrac{I^{\text{recent}}}{I^{\text{historical}}}$

<!-- Ernesto Jardim, Manuela Azevedo, Nuno M. Brites, Harvest control rules for data limited stocks using length-based reference points and survey biomass indices, Fisheries Research, Volume 171, November 2015, Pages 12-19, ISSN 0165-7836, https://doi.org/10.1016/j.fishres.2014.11.013 -->


$I^{\text{recent}}$ is the mean index from the most recent years, $I^{\text{historical}}$ is the mean from years preceding that for $I^{\text{recent}}$.
The number of years for $I^{\text{recent}}$ and $I^{\text{historical}}$ can vary. Two options were explored:

Iratio_23  $I^{\text{recent}}$ is from the preceding 2 years, e.g., 2018-2019
           $I^{\text{historical}}$ is from the 3 years preceding $I^{\text{recent}}$, e.g., 2015-2017

Iratio_55  $I^{\text{recent}}$ is from the preceding 5 years, e.g., 2015-2019
           $I^{\text{historical}}$ is from the 5 years preceding $I^{\text{recent}}$, e.g., 2010-2014

### IDX

<!-- Cox et al. Res Doc in press -->


## SP MPs
- State-space surplus production model (should be documented in gfmp appendix?) with prior for intrinsic rate of increase from 2011 assessment.
- Two ramped harvest control rules:
a. 80-40% BMSY as the USR, LRP
b. 40-10% B0 as the USR, LRP
- Two assessment frequencies (5 and 10 years)
- Fixed TAC between assessments

#### Reference MPs

In addition to the candidate MPs, it is important to include reference MPs. Provisionally, we suggest the following reference MPs:

* No fishing
* Fishing at F/F~MSY~
* Fishing at 0.75 F/F~MSY~
* Maintaining the current TAC

The purpose of reference MPs is not to explore viable management strategies but to bound the range of expected or possible performance and contextualize whether differences between performance statistics among MPs are meaningful [@punt2016]. For example, the "no fishing" reference MPs provides information on maximum possible stock levels and the maximum possible rate of rebuilding under a rebuilding scenario. The "fishing at 0.75 F/F~MSY~" MP illustrates performance under an omniscient manager with perfect information. The MP that maintains the current TAC is included not because we think it is necessarily a good management strategy but illustrates what is likely the default had the framework not been implemented and illustrates the long-term performance expectations given current exploitation levels.


### STEP 5: SIMULATION OF THE APPLICATION OF THE MANAGEMENT PROCEDURES  {#sec:approach5}

Once the objectives, performance metrics, calibrated OMs and MPs are fully specified, a closed-loop simulation framework (Figure \@ref(fig:mse-chart)) can be applied to test relative performance of the MPs with respect to meeting the stated objectives.

We recommend beginning with a satisficing step, where trial simulations are run to screen out MPs that do not meet a basic set of performance criteria [@miller2010].
For example, in our illustrative Rex Sole case study (Appendix \@ref(app:mse-rex)), we screened out MPs that did not achieve a long-term 90% probability of keeping the stock above the LRP (LT P40 $\geq$ 0.9) and a short-term 75% probability of yield above 50% MSY (STY $\geq$ 0.75).
This resulted in **XX** final MPs, plus the four reference MPs.

DLMtool is designed to follow standard MSE operating procedure (Figure \@ref(fig:mse-chart)), where the OM is used to simulate the various data streams required by the MP at each time step, then the biomass is projected forward under the prescribed MP at each subsequent time step until the projection period is complete.
Performance is then evaluated through calculation of performance statistics in the OM.
DLMtool makes use of the C++ programming language and parallel processing, making the simulations computationally efficient [@carruthers2018].

For each OM-MP combination, multiple replicate projections are run to account for observation and process errors in the data streams.
This is achieved by adding stochastic noise to the data (e.g, indices of abundance) before passing them to the MP. Coefficients of variation in the data should be consistent with those in historical observations [@rademeyer2007]. Typically, at least 100 replicate simulations are run for each OM/MP combination.
We suggest selecting sufficient replicates so that the rank order of MPs across the performance metrics remains consistent regardless of additional iterations [@carruthers_user_2019].


### STEP 6: PRESENTATION OF RESULTS AND SELECTION OF MANAGEMENT PROCEDURE  {#sec:approach6}




