
## STEP 2: SELECTION OF OBJECTIVES AND PERFORMANCE METRICS  {#sec:approach2}

Clear management and fishery objectives and the performance metrics that measure them must be identified.
Objectives may span a wide range of policy or legistated objectives (e.g., maintaining the stock above the LRP), economic objectives (e.g., average catch or variability in catch), and cultural objectives (e.g., maintaining minimum required access to the stock or specific fishing areas).
Fully quantified objectives include a metric, the desired probability of success, and a time frame to achieve the objective (e.g., probability of maintaining the stock above the LRP is greater than 0.95 [19 times out of 20], over 1.5 generations of the stock).
Performance metrics are quantified measures of the objectives, calculated in the OM at each time step of the projections.

The original rebuilding plan objectives for Inside Yelloweye Rockfish were published in 2018 [@ifmp2018; their Appendix 9]. The original rebuilding plan objective was to
rebuild the stock above the LRP over 80 years with 56% probability of success; with the additional milestone to achieve positive biomass trends within each 10 year period.
The MP that was agreed upon to meet these objectives was to maintain the combined TAC (commercial, recreational, FSC, biological survey) below 15 tonnes annually [@ifmp2018].

Here we present a set of refined objectives and associated performance metrics for the rebuilding plan for Inside Yelloweye Rockfish.
Key provisional conservation objectives are guided by the PA Framework
[@dfo2006; @dfo2009], rebuilding plan guidance [@dfo2013], and regional precedent [@cox2019; @cox2020].
Additional objectives related to fisheries yield and variability in annual fisheries yield are based on precedents in other DFO Pacific Region analyses [e.g., @cox2008a; @forrest2018; @cox2019; @cox2020].

The proposed core conservation objective is:

1. Rebuild the stock above the LRP over 56 years (1.5 generations) with at least 95% [19 times out of 20] probability of success.

*TODO: DANA please can you add something here about the choice of 1.5 generations. I think this came from the outside YE rebuilding plan [@cox2020]. Please also make a short note about the difference in GT between the inside and outside stocks and refer to the biological data appendix. I have added a todo there as well*

The rebuilding time-frame was modified from 80 years in the original rebuilding plan [@ifmp2018] to 56 years to reflect ... **xxx**
The probability of success was increased from 56% to 95% to reflect rebuilding guidance that the probability of rebuilding should be high, and international best practice, where policies in numerous jurisdictions aim to keep stocks above the LRP with 90-95% probability [18 to 19 times out of 20][@sainsbury2008; @mcilgorm2013].

We also propose the following additional objectives:

2. Maintain a fishing mortality rate below the fishing mortality rate at maximum sustainable yield (*F*~MSY~) with some probability.

3. Given the above conservation objectives are achieved, maximize short- and long-term fisheries catch.

4. Given the above conservation objectives are achieved, minimize variability in fisheries catch from year to year.

In addition, we propose refining the milestones identified in the original rebuilding plan as follows:

5. Achieve positive biomass trends within each 10 year period *for as long as the stock remains below the LRP*.

Current rebuilding guidance only provides for objectives to build stocks out of the critical zone [@dfo2013], with milestones intended to ensure progress is achieved during the rebuilding process.
The 10 year period identified in the milestones for the Inside Yelloweye Rockfish rebuilding plan [@ifmp2018] reflected an assumption that rebuilding could be very slow for this stock.
We adjusted the milestone to reflect the assumption that, once the stock is rebuilt (i.e., no longer in the critical zone), the milestone would no longer be required.
The rebuilding guidance does discuss having longer-term objectives to keep rebuilding stocks into the healthy zone.
However, this is supposed to be achieved beyond the period and scope of the rebuilding plan [@dfo2013].
We have interpreted this milestone in its strictest sense (i.e., the rebuilding plan is to rebuild the stock out of the critical zone), but the milestone could be revised in the future to require that positive biomass trends should be achieved until the stock is in the healthy zone.
This is a decision to be made at Step 1 of future processes by fisheries managers, First Nations and stakeholders.

We propose the following performance metrics to measure the objectives, where *B* represents spawning biomass, MSY refers to maximum sustainable yield, *B*~MSY~ refers to equilibrium spawning biomass at MSY, *F*~MSY~ refers to the fishing mortality that produces MSY over the long term, and GT represents generation time:

*TODO: define the years for calculating LRP 1.5 GT, LRP 1 GT, USR 1.5 GT and LT C20*

  * LRP 1.5 GT		P[*B* > 0.4 *B*~MSY~] after 1.5 GT (56 years)
  * LRP 1 GT		    P[*B* > LRP] after 1 GT (38 years)
  * USR 1.5 GT		P[*B* > USR] after 56 years

  * ST C10		P[Catch > 10 t] during 2020-2029
  * ST C15    P[Catch > 15 t] during 2020-2029
  * ST C20		P[Catch > 20 t] during 2020-2029
  * LT C20		P[Catch > 20 t] after 1 Generation time
  * ST AADC   P[AADC during 2020-2029 < AADC during 2012 - 2019]
  
AADC represents average absolute deviation in catch over $n$ years and is defined as:

$AADC = \dfrac{1}{n-1}sum_{y=2}^n \mid C_y - C_{y-1} \mid$

The baseline period for AADC (2012 - 2019) was selected as this is the period since the start of the 15 t TAC.

We include the performance metric LRP 1 GT as a check that the MPs do not crash the stock in the short term. *TODO: is this correct?*

In cases where performance metrics are calculated over a range of years, care needs to be taken to clearly report how summary statistics are calculated.
@anderson2020gfmp suggested calculating performance statistics across replicates and the entire time window as defined for the performance metric.
We follow this protocol here.
For example, we averaged the short-term (ST) catch metrics over only the years 2020-2029.

### COSEWIC CONSIDERATIONS {#sec:approach2-cosewic}

*TODO: Clean this up. RF Moved these COSEWIC metrics from MP section but not sure if they are needed. Go through all these and delete if they were not used or explain why they are here ... OR do we need to add them to results if not already? *

*TODO: update: Make short appendix of COSEWIC metrics*

COSEWIC and DFO have different criteria for assessing the status of marine fish stocks. DFO focuses on current status relative to some reference state or threshold, while COSEWIC criteria (based on IUCN Red List categories) are more focused on the probability of decline over past generations and the probability of continued declines in the future e.g. Criteria A1,2,3,or 4 in [@cosewic2015]. In order for this analysis to inform the COSEWIC re-assessment, we report the probability that the stock has declined at least 30%, 50%, and 70% over the past 3 generations. <!--Not sure how the whole discussion around extinction risk (COSEWIC indicator E) came out. From the emails I read this quantitative metric is rarely used by COSEWIC for marine fishes (MJB) -->

#### COSEWIC Metric A

P70 - Probability that population decline hasn't exceeded 70% over 3 generations
where generation time = 38 years for inside yelloweye

P[1 - B_2019/B_1918 < 0.7]

P50 - Probability that population decline hasn't exceeded 50% over 3 generations

P[1 - B_2019/B_1918 < 0.5]

P30 - Probability that population decline hasn't exceeded 30% over 3 generations

P[1 - B_2019/B_1918 < 0.3]

#### Extinction Risk - COSEWIC E

We propose two potential thresholds of 2% B_0 and 5% B_0 to quantititively calculate risk for future extinction.
Using a projection period of 100 years, we calculate the probability that the stock remains above 2% and 5% B0:

`2% B_0` = P[B_y > 0.02 B_0]
`5% B_0` = P[B_y > 0.05 B_0]
