# DISCUSSION {#sec:discussion}

We applied a new MP Framework for Pacific groundfishes [@anderson2020gfmp] to evaluate the ability of alternative MPs to meet rebuilding objectives for Inside Yelloweye Rockfish.
This is the first application of the MP Framework for decision-making purposes.

We evaluated the performance of 31 data-limited MPs (and three reference MPs) with respect to meeting the objectives described in Section \@ref(sec:objectives-metrics).
We screened out MPs that did not meet both satisficing criteria LRP 1.5GT > 0.9 and ST C10 > 0.50 across the OM reference set scenarios, resulting in `r gfutilities::number_to_word(length(mp_sat))` remaining MPs (`r gfutilities::commify(sort(mp_sat))`).
All remaining MPs achieved the conservation metrics LRP 1.5 GT, USR 1.5GT and LRP 1GT with greater than 0.98 probability (49 times out of 50) across all four OM reference set scenarios.
This was largely because none of the reference set OMs estimated the stock to be in the critical zone in 2020---the start of the projection period.
Within the two OM robustness set scenarios, OM Scenario (B), which simulated higher variability in the future HBLL survey, performed similarly to the OM reference set scenarios.
However, under OM Scenario (A), the Low M scenario, the probabilities of meeting the performance metric LRP 1.5GT ranged from 0.75 (75 times out of 100) to 0.9 (nine times out of 10), with the current MP (CC_15t) having the lowest probability in this range.

Whereas the rebuilding plan guidance [@dfo2013] only describes objectives related to rebuilding, we also evaluated performance of MPs with respect to three average-catch objectives and one catch-variability objective.
The CC_10t and CC_15t MPs, by definition, met their respective ST C10 and ST C15 performance metrics.
The Islope MPs showed some contrast across MPs within the reference set for ST C10 and ST C15, depending on the MP configuration and the OM scenario.
The OM robustness set scenarios generally produced lower probabilities of meeting the ST C10 metric.

We presented a number of visualizations to show trade-offs among conservation and catch objectives [see also @anderson2020gfmp].
The visualizations present trade-offs in different tabular and graphical formats, intended to support the process of selecting the final MP.
Because all the MPs met the LRP 1.5 GT objective under the OM reference set scenarios, there were no strong trade-offs between conservation and catch objectives.
Of the two OM robustness set scenarios, trade-offs were most apparent under the Low M scenario, where the probability of meeting the LRP 1.5GT objective decreased as the probability of achieving an ST C10 increased.

We found the radar plot visualizations difficult to interpret.
While these plots can be useful for rapid visualization of multiple trade-offs, and have been recommended for visualization of MSE results [@punt2017], they become more difficult to interpret as more metrics ("spokes") are added.
They are also very sensitive to the order in which the metrics are placed, and have been shown to be less interpretable that Cartesian plots [@diehl2010; @feldman2013; @albo2016]. We presented radar plots here to gauge interest from RPR participants and solicit feedback on whether to include them in future applications of the MP Framework.

## NATURAL MORTALITY {#sec:discussion-m}

The purpose of the robustness set is to explore OM formulations that represent alternative  hypotheses to those in the reference set [@rademeyer2007; @punt2016].
Candidate MPs should perform well across both OM reference and robustness scenarios [@rademeyer2007].
In our study, the two OM robustness set scenarios performed differently from the OM reference set scenarios, especially OM Scenario (A).
This low mortality/low productivity scenario ($M \sim \textrm{Lognormal}(0.025, 0.2)$) was the only one where the median biomass was estimated to be in the critical zone at the start of the projection period.
For all other OM scenarios, we sampled from a probability distribution for *M* with mean 0.045 y^-1^, which matched that used in the previous stock assessment [@yamanaka2011].

The rate of natural mortality of fish populations is of one of the most important, yet most difficult parameters to estimate. 
Numerous methods have been developed to estimate *M* from available life history parameters.
An [app](http://barefootecologist.com.au/shiny_m.html) developed by NOAA scientists that estimates *M* using various published empirical methods was populated with inside Yelloweye Rockfish parameters. Estimates of *M* ranged from 0.03 to 0.17, depending on the empirical method. Other Yelloweye Rockfish assessments have used lower values for *M*, closer to or lower than those used in OM Scenario (A) (mean 0.025 y^-1^).
For example, the recent rebuilding plan for the outside stock of Yelloweye Rockfish estimated median values for *M* between 0.031 *y*^-1^ and 0.044 *y*^-1^, depending on the OM [@cox2020].
The 2008 COSEWIC assessment and status report for inside and outside Yelloweye Rockfish stocks [@cosewic2008] used a value of *M* = 0.02 *y*^-1^, citing the 2001 stock assessment for the inside stock [@yamanaka2001].
Similarly, stock assessments for the southern Gulf of Alaska stock of Yelloweye Rockfish have used a value of *M* = 0.02 *y*^-1^ [@wood2019].

It is likely that natural mortality rates have varied over time, due to changes in predator populations in the Strait of Georgia. 
Yelloweye Rockfish occupy a relatively high trophic position [@olson2020] and Steller Sea Lions, Orca Whales (*Orcinus orca*) and Chinook Salmon (*Oncorhynchus tshawytscha*) are the only predators of Yelloweye Rockfish listed in a large data-base of predator-prey interactions (database assembled for @dunne2016; @szoboszlai2015). 
Populations of all three predator species have experienced large fluctuations in the last century.
Steller Sea Lion abundance was greatly reduced due to hunting and predator controls, but have now recovered to historical levels [@olesiuk2018; and see Appendix F]. 
The Southern Resident population of Orca Whales is endangered and the Northern Resident population is threatened [@cosewic2008b]. The cause of decline for both populations is attributed to the declining abundance of Chinook Salmon [@ford2010].
Pacific Halibut have also been observed preying on Yelloweye Rockfish in the Gulf of Alaska [@livingston2017]; however, Pacific Halibut are not very abundant in inside waters (see data for 2018 IPHC survey in @anderson2019synopsis). 
Lingcod are likely predators of juvenile Yelloweye Rockfish as they are known predators of rockfish species. 
However, stomach content studies are often not able to resolve rockfish species beyond unidentified rockfish (i.e. @beaudreau2007, @livingston2017).
Lingcod in the Strait of Georgia also suffered major population declines and were thought to have been fished down to 2% of historic levels in 1990 but the population has increased since [@logan2005; @holt2016]. 
Future projects might investigate the effects of time-varying natural mortality on Inside Yelloweye Rockfish.

## ROCKFISH CONSERVATION AREAS {#sec:discussion-rca}

As part of the rockfish conservation strategy, 164 Rockfish Conservation Areas (RCAs), in which fisheries targeting or catching rockfish as bycatch are prohibited, were established in BC waters between 2004-2006 [@yamanaka2010]. 
There are 130 RCAs in Area 4B (Figure \@ref(fig:map-4B)) that protect an estimated 267 square kilometres of rockfish habitat, amounting to 22% of available rockfish habitat in inside waters [@haggarty2018]. 
Although RCAs were established as one measure to help rebuild rockfish populations [@yamanaka2010], this analysis does not consider any possible effects of the closures. 
Remotely Operated Vehicle (ROV) surveys of RCAs in inside waters found that there was no difference in the abundance or size of Yelloweye Rockfish inside RCAs at the time of study (3-7 years after RCA establishment) [@haggarty2016b]. 
It is expected that, given the late age-at-maturity and longevity of rockfishes, it will take upwards of 20 years for populations to show responses to closed areas [@starr2015]. 
The RCAs in the inside waters have now been in place for 14 to 16 years, so we might expect to find increased densities and sizes of rockfish in RCAs soon. 
DFO, in partnership with biologists from the Washington Department of Fish and Wildlife (WDFW) and the National Ocean and Atmospheric Administration (NOAA), undertook an ROV survey of several RCAs in the Strait of Georgia in the fall of 2018 on board the CCGS Vector. 
However, results from this survey were not available in time to be included in this project. 

## STOCK STATUS {#sec:discussion-status}

The rebuilding plan for the inside stock of Yelloweye Rockfish was triggered by the 2010 stock assessment [@yamanaka2011], which estimated the stock to be below the LRP with high probability.
Out of all the reference  and robustness set OMs explored in our analysis, only OM Scenario (A), Low M, estimated median spawning biomass to be below the LRP in 2010.
In all OM scenarios, log recruitment deviations began to increase after 2000, albeit still below zero, likely tracking slight increases in the HBLL index during this period. 
The 2010 assessment used a surplus production (SP) model, with fundamentally different structural assumptions to the SRA used for conditioning OMs in our analysis.
As a check, we fit a SP model, similar to that used by @yamanaka2011, and obtained much lower biomass and stock status estimates than from the reference set SRA OMs.
Furthermore, the estimate of *B*~MSY~ was higher for the SP model than our OM Scenario (1), while the *F*~MSY~ estimate from the SP model was lower than those from the reference set SRA models, indicating lower productivity in the SP model.
The fact that the SP model had lower estimated productivity and biomass, and higher *B*~MSY~ would lead to a more pessimistic assessment of stock status.
The SP-fitting exercise suggests that model structure, rather than the addition of ten years of new data since the last assessment, was a major factor contributing to different perceptions of stock status between the current OMs and the previous assessment.

In a recent evaluation of the outside stock of Yelloweye Rockfish, @cox2020 found similar differences between their age-structured OMs, which estimated stock status to be above the LRP, and the 2014 SP-based assessment [@yamanaka2018yelloweyeoutside], which found the stock to be below the LRP, triggering a rebuilding plan.
@cox2020 noted that structural differences between SP and age-structured models would be expected to produce different results, particularly due to differences in the formulation of productivity.
We were able to mimic the stock status estimates of @yamanaka2011 when we forced the stock to have lower productivity in OM Scenario (A), although the mean value of *M* used in OM Scenario (A) was lower than that used by @yamanaka2011 to develop the productivity prior for their SP model.
@cox2020 noted that age-structured models allow for lags in recruitment to fisheries, surveys, and the spawning stock, characteristics that can promote resilience and are more realistic for a long-lived species like Yelloweye Rockfish.
These differences are controlled by fishery selectivity-at-age, survey selectivity-at-age and maturity-at-age, respectively, in age-structured models and can be over-simplified in aggregate SP models.
Our OM Scenario (4), where we estimated survey selectivity-at-age, resulted in lower estimates of stock status, implying that assumptions about selectivity were a contributing factor to perceptions of stock status (see Section \@ref(sec:discussion-uncertainties-selectivity)), most likely resulting from impacts on other parameter estimates such as *R*~0~ and autocorrelation in recruitment.
@cox2020 also noted that their SP-based MPs tended to underestimate biomass, which we also found in the current study, where the SP MPs generated no catch in the first decade of the projections.

Despite differences in perception of stock status among some of our OMs, and between this and the previous stock assessment, we note that the MP Framework provides a method for integrating across the major uncertainties in stock status and reference points (see Section \@ref(sec:discussion-implicit)) that are prevalent for this stock.
In particular, the inclusion of OM Scenario (A) in the robustness set provides decision-makers with an alternative view of stock status and performance of MPs.

## KEY UNCERTAINTIES {#sec:discussion-uncertainties}

### Selectivity {#sec:discussion-uncertainties-selectivity}

Selectivity was a major source of uncertainty in our OMs.
There are no available age-composition data for commercial or recreational fisheries, and none from the Dogfish survey.
We therefore fixed selectivity for all these gears.
Commercial and recreational selectivities were set to match those reported for the outside stock [@cox2020] and we set selectivity in the Dogfish survey to mirror the value used for the HBLL survey.
However, it was noted during the Outside Yelloweye Rebuilding process that additional biological sampling should be undertaken to inform the selectivity of commercial, recreational and FSC catches [@dfo2020], and this recommendation equally applies to the inside population. Full biological data, including otoliths from Yelloweye Rockfish were collected on the Dogfish survey in 2019 for the first time.
Although the ages were not yet available for this work, they may inform selectivity of the Dogfish survey for future work. 
We also initiated project in August 2019 to compare the HBLL and Dogfish gear by fishing some of the Dogfish survey sites with both the HBLL and Dogfish survey gear. These data may also inform the comparability of the two surveys.  

Age-composition data from the area 4B surveys were sparse and have only been collected in recent years.
Initial attempts to estimate selectivity in the HBLL survey (coupled with equal weighting between the HBLL and Dogfish survey) resulted in implausible estimates of age-at-full-selectivity and a strong retrospective pattern in biomass estimates.
We therefore fixed age-at-full-selectivity at 22 *y*, and upweighted the Dogfish survey likelihood component, which greatly improved the retrospective behaviour.
To separate the effects of upweighting the Dogfish survey from fixing HBLL selectivity, we estimated HBLL selectivity in OM Scenario (4), which slightly changed the perception of stock status.

While we could have explored other fixed selectivity assumptions, we believe we used the most plausible values, and, for the HBLL survey, included an alternative OM scenario in the reference set.
Future applications of the MP Framework for this stock could explore other selectivity OM scenarios.


### Historical catch {#sec:discussion-uncertainties-catch}

The other major source of uncertainty in our analyses is the magnitude of historical commercial and recreational catch. Uncertainty regarding commercial catch is due to reporting of rockfishes other than Pacific Ocean Perch in an aggregate category before 1950, and large uncertainty in the magnitude of unreported catch during the period 1986--2005.
A reconstruction of historical catch data to 2005 was done by @haigh2011, which attempted to parse out Yelloweye Rockfish from the aggregated rockfish category and to account for discarded fish.
The reconstructed catches were used in the previous stock assessment [@yamanaka2011].
While there has been some controversy over reconstructed catch data, for both the outside and inside Yelloweye stocks, re-evaluation of the reconstruction was outside the scope of this work and it remains the best available time series of historical catches.
We therefore followed the same approach to reconstructing historical recreational catch data and estimating current recreational catch data as @yamanaka2011.
We evaluated the effect of doubling the nominal catch data for the period 1986--2005 in OM Scenario (2) but performance of MPs was not appreciably different from other OM reference set scenarios.

We deviated from @yamanaka2011 in our treatment of FSC catch. They applied an algorithm to explicitly estimate FSC catch, based on assumptions about consumption rates.
After discussions with Fisheries Biologists who work with local First Nations in the northern and southern portions of Area 4B, we elected to include FSC catches with commercial catches in the northern portion, because most of the rockfish catch is understood to be caught under dual fishing licences and would therefore be included in DFO commercial catch databases.
We elected to assume FSC catches in the southern region were accounted for in recreational catches, because most of the rockfish catch is caught from small vessels, so effort, at least, is likely already counted by DFO overflights.
We recognize the large uncertainties surrounding FSC catch.
Future applications of the MP Framework for this stock would benefit from more detailed collaborative work with First Nations to quantify contemporary and historical FSC catch in Area 4B.

## IMPLICIT VS. EXPLICIT KNOWLEDGE OF LIMIT REFERENCE POINTS {#sec:discussion-implicit}

This MP Framework, and all MSE processes, differ from conventional stock assessments in the way science advice is delivered [@anderson2020gfmp].
In most BC groundfish stock assessments [e.g., @yamanaka2011; @starr2017; @forrest2019], catch advice is presented in the form of decision tables, where probabilities of breaching reference points (e.g., probability of the stock falling below the LRP) are presented over a range of possible future TAC levels.
This approach depends on explicit reporting of reference points and estimation of stock status.
Following the production of a decision table, it is then the job of the decision-makers to select a future TAC based on the probabilities presented, taking into consideration other factors such as the economic needs of the fishery and some level of risk tolerance.
In this process, consideration of risk occurs at the final step of the decision-making process and may not always be transparent or be related to pre-agreed objectives.

MP frameworks differ from conventional assessments in two key ways: (1) reference points and stock status are not necessarily explicitly reported; and (2) objectives related to the probability of breaching reference points must be agreed upon at the beginning of the process, (i.e., Step 2 of the best practices).
Reference points and stock status are therefore still an integral component of the framework, but they are calculated in the OMs and are built into the performance metrics.
Critically, agreement on acceptable risk (e.g., acceptable probabilities of breaching reference points) must be reached at the beginning of the process so that performance metrics and satisficing criteria can be established.

For many stocks, especially data-limited stocks, it is not possible to reliably estimate biological reference points or estimate stock status.
MP frameworks such as this one may be especially important for these stocks.
The Sustainable Fisheries Framework and the Fish Stocks provisions of the *Fisheries Act* require that fish stocks be maintained at sustainable levels, and particularly above the LRP.
This framework implicitly preserves the intent of these policies despite the fact that reference points and stock status are not explicitly emphasized.

## REASSESSMENT FREQUENCY AND TRIGGERS {#sec:discussion-triggers}

In general, the purpose of an MP framework is to identify and select a robust MP that can be left in place for an agreed amount of time.
Interim checks between assessments are also recommended to ensure the selected MP is performing as expected.
In addition to the MSE best practice steps, @carruthers2018 describe a final evaluation step, where performance of the selected MP is formally reviewed once it has been implemented.
Departures from an MP's expected performance have been termed "exceptional circumstances".
These may occur when the observed system dynamics fall outside the range of OM scenarios specified in the OMs over which the MP was demonstrated to be robust [@butterworth2008].

Evidence for exceptional circumstances, occurring within the recommended assessment interval, would trigger a review of the OM(s) and MP, possibly resulting in a new OM, or an adjustment to the selected MP [@carruthers_hordyk_2018].
These authors list several examples of MSEs where formal protocols for detecting exceptional circumstances have been established.
In general, formal protocols include monitoring the biomass index, catch, and other data-types such as age-composition data, and comparing observations to the OM predictions.
An example of a trigger for re-evaluation could be the observed index of abundance falling outside the 90% confidence interval of the OM-projected index.
See @carruthers_hordyk_2018 for further recommendations on formal evaluation procedures.
Informal evaluation procedures, via feedback from stakeholders or visual comparison of observed data vs. projected data, can also be used to detect exceptional circumstances [e.g., @cox2008a].

Satisficed MPs in the current analyses included constant catch MPs and annual Islope MPs. All of the index-based MPs were also evaluated at five-year intervals. While all of these MPs met the LRP 1.5GT criteria, none of them met the ST C10 criteria.
Therefore, if an index-based MP is selected, we recommend annual updates.
In line with guidance for rebuilding plans in Canada [@dfo2013], we recommend re-evaluation of the performance of the selected MP at least every three years.

\clearpage

# ACKNOWLEDGEMENTS

We are grateful to Adam Keizer and Maureen Finn (Groundfish Management Unit), and Roger Kanno (Sustainable Fisheries Framework Coordinator) for helpful discussions and guidance regarding objectives for the rebuilding plan.

We are very grateful to Bob Bocking, Cheri Ayers and Christa Rusel, fisheries consultants working with local First Nations; and Mark Fetterly, Aleta Rushton and Patrik Zetterberg from DFO, who provided very helpful advice regarding FSC catch.

Ross Claytor and Dwayne Lepitzki from COSEWIC provided useful guidance on the development of performance metrics that we be of use for COSEWIC assessments. 

Strahan Tucker and the pinniped team, DFO, provided data on Pinniped abundance and rockfish consumption rates.
Spencer Wood, The Natural Capital Project, Stanford University, searched their large predator-prey database for us.

Rowan Haigh provided advice on the historical catch reconstruction.

We thank Tom Carruthers and Adrian Hordyk (UBC) for early guidance on this rebuilding plan and their cheerful willingness to add new features to the DLMtool software on request.

Finally we thank Dayv Lowry (WDFW) and Kendra Holt (DFO) for insightful reviews that greatly improved the working paper.

