# PINNIPED PREDATION {#app:pinniped-predation}

In response to concerns about increasing populations of Harbour Seals (*Phoca vitulina*), Steller Sea Lions (*Eumetopias jubatus*), and California Sea Lions (*Zalophus californianus*), @yamanaka2011 explicitly explored the potential impact of consumption of Yelloweye Rockfish by pinnipeds in inside waters. 
To do so, they used published and unpublished census data for pinniped populations and assumptions about consumption rates of rockfishes, based on bioenergetic requirements and existing pinniped diet information. 
The Rockfish component of the diet available for the three species of pinnipeds was resolved to the genus level (*Sebastes* spp.) because bone fragments and otoliths recovered from scat samples cannot be identified to species.
Therefore, @yamanaka2011 assumed that the fraction of Yelloweye Rockfish in pinnipeds' diets, as a percentage of total *Sebastes* spp., was the same as their mean occurrence in monitoring surveys (longline, jig and trawl surveys), which they calculated to be 25%. 
The same fraction was used for all three pinniped species despite the fact that the ecology of Harbour Seals, California Sea Lions and Steller Sea Lions differs significantly, as do their maximum weights: 80 kg, 390 kg, and 1100 kg, respectively [@ford2014].

In comparison to other common rockfish in the Strait of Georgia, such as Yellowtail, Copper, and Puget Sound Rockfishes, Yelloweye Rockfish are larger and dwell deeper. As a result, Yelloweye Rockfish are less likely to be consumed by smaller predators such as Harbour Seals and California Sea Lions.
Furthermore, Steller Sea Lions, Orca Whales (*Orcinus orca*) and Chinook Salmon (*Oncorhynchus tshawytscha*) are the only predators of Yelloweye Rockfish listed in a large data-base of predator-prey interactions (database assembled for @dunne2016; @szoboszlai2015). 
DFO pinniped researchers have been undertaking a major survey program to identify pinniped prey by species, using genetic analysis of scat samples. 
Preliminary results have not identified Yelloweye Rockfish in scat from Harbour Seals (n=1248) or California Sea Lions (n=116). These same results suggest that Yelloweye Rockfish make up 0.1% of the diet of Steller Sea Lions in the Strait of Georgia (n=331) and West Coast of Vancouver Island (n=340) (S. Tucker, DFO Science, unpublished data). 
It should be noted that this analysis is limited in temporal and spatial scope and the sample sizes for the data that have been analyzed to date are relatively small. 
In addition, the preliminary data available are the percent of species' DNA reads relative to total DNA reads and are not yet calibrated in terms of biomass yields to correct for methodological and biological biases (S. Tucker, DFO Science, pers. comm., April 7, 2020).    

Steller Sea Lions were decimated in BC, by hunting and directed predator culls, but their abundance began to increase following protection in 1970 [@ford2014; @olesiuk2018]. Inside Yelloweye Rockfish are at higher risk of predation by Steller Sea Lions during the winter, because sea lions aggregate at breeding rookeries along the outer coast during the summer, although a small number of animals (~500) have recently been observed year-round in the Strait of Georgia [@majewski2020].
Winter population estimates for sea lions are less certain than summer estimates because the animals spend more time in the water than hauled out on land, and are more widely dispersed, making them more difficult to count.
Steller Sea Lion abundance in BC is approximately 1.25 fold higher in the winter, as animals from adjacent jurisdictions overwinter in BC waters [@olesiuk2018].
@yamanaka2011 found that the proportion of Steller Sea Lions wintering in inside waters was fairly constant over time, at 4.8% of the winter counts in Southern BC. 
Using this proportion, they estimated the number of Stellar Sea Lions in 4B decreased to a low of around 500 animals in 1970 and then increased to approximately the abundance recorded at the beginning of the time series in 1913 (1,897 in 1913, vs. 1,837 in 2010).
Since 2010, Steller Sea Lion counts in BC have continued to increase [@olesiuk2018]; however, the estimated abundance from the 2017 survey falls within the CI of the 2013 estimate [@majewski2020]. 

Mortality rates of Yelloweye Rockfish from Steller Sea Lion predation were probably lower in the middle of the time series, when predator controls of Steller Sea Lions were in place (1912-1968 [@ford2014]), and have likely increased with the recovery of the population to a level similar to, or higher than, at the beginning of the time series.
<!-- please clarify the above sentence. The middle of which time series? 1912 pre-dates our catch time series, which started in 1918. What level have they recovered to? At the 1918 beginning of our time series, predator controls were already in place -->
Following the methods in @yamanaka2011, we make a crude estimate of the total tonnes of Yelloweye Rockfish consumed by the average annual abundance of Steller Sea Lions (909 animals between 1979-2008), which collectively require 5939 tonnes of food annually. 
Using the proportion of Yelloweye Rockfish found in the recent scat analyses (0.1%), we estimate that Steller Sea Lions consume approximately 5.9 tonnes/year of Yelloweye Rockfish. 
This estimate is lower than the estimated consumption by all three species of pinnipeds reported in Yamanaka et al. (2011): 10 tonnes for Steller Sea Lions, 72 tonnes by Harbour Seals and 23 tonnes by California Sea Lions, for a possible total of 105 tonnes (lower bound 29, upper 400).

<!-- Do we need to report an estimate at all? We are not using it for anything and we have made a pretty good case that Strachan's numbers are preliminary. As a reviewer I would be wondering why the estimate was in the working paper. Maybe best to leave out our estimates and use this appendix to underline that we have not modelled pinniped predation as an additional source of mortality based on preliminary reduced estimates of the rates of predation by the three pinniped species (0%, 0% and 0.1%). We suggest future work could attempt to model a time-varying mortality component, based on changes in Steller Sea Lion abundance, once more reliable diet estimates are published. -->

