# My understanding is that this is no longer needed
# but I could be wrong. -SA 2020-02-05

# Dogfish survey data for inside yelloweye rebuilding plan.
# Uses gfdata

fe <- gfdata::run_sql("GFBioSQL", "SELECT
  S.SURVEY_SERIES_ID,
  SURVEY_SERIES_DESC,
  S.SURVEY_ID,
  SURVEY_DESC,
  YEAR(FE_BEGIN_RETRIEVAL_TIME) YEAR,
  FE.FISHING_EVENT_ID,
  FE_START_LATTITUDE_DEGREE + FE_START_LATTITUDE_MINUTE / 60 AS LATITUDE,
  -(FE_START_LONGITUDE_DEGREE + FE_START_LONGITUDE_MINUTE / 60) AS LONGITUDE,
  FE_END_DEPLOYMENT_TIME,
  FE_BEGIN_RETRIEVAL_TIME,
  FE.GROUPING_CODE,
  GROUPING_DESC,
  GROUPING_DEPTH_ID,
  FE_BEGINNING_BOTTOM_DEPTH AS DEPTH_M,
  FE_BOTTOM_WATER_TEMPERATURE,
  LLSP.HOOK_CODE,
  HOOK_DESC,
  SKATE_COUNT,
  LGLSP_HOOK_COUNT,
  0.0024384 * 0.009144 * LGLSP_HOOK_COUNT AS AREA_SWEPT_KM2 --0.024384 = 8 ft hook spacing (to calculate line length with hook count); 0.009144 = 2*gangion length (= area width)
  FROM FISHING_EVENT FE
  INNER JOIN TRIP_SURVEY TS ON FE.TRIP_ID = TS.TRIP_ID
  INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
  INNER JOIN SURVEY_SERIES SS ON SS.SURVEY_SERIES_ID = S.SURVEY_SERIES_ID
  INNER JOIN LONGLINE_SPECS LLSP ON LLSP.FISHING_EVENT_ID = FE.FISHING_EVENT_ID
  INNER JOIN GROUPING G ON G.GROUPING_CODE = FE.GROUPING_CODE
  INNER JOIN HOOK H ON H.HOOK_CODE = LLSP.HOOK_CODE
  WHERE S.SURVEY_SERIES_ID IN (76)")
names(fe) <- tolower(names(fe))


ye_catch <- gfdata::run_sql("GFBioSQL", "SELECT
  FEC.FISHING_EVENT_ID,
  SUM(CATCH_COUNT) YE_COUNT
  FROM FISHING_EVENT_CATCH FEC
  INNER JOIN CATCH C ON C.CATCH_ID = FEC.CATCH_ID
  INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = FEC.TRIP_ID
  INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
  WHERE C.SPECIES_CODE IN ('442') AND SURVEY_SERIES_ID = 76
  GROUP BY FEC.TRIP_ID,
  FEC.FISHING_EVENT_ID,
  C.SPECIES_CODE
  ORDER BY FEC.FISHING_EVENT_ID")
names(ye_catch) <- tolower(names(ye_catch))

dogfish_catch <- gfdata::run_sql("GFBioSQL", "SELECT
  FEC.FISHING_EVENT_ID,
  SUM(CATCH_COUNT) DOGFISH_COUNT
  FROM FISHING_EVENT_CATCH FEC
  INNER JOIN CATCH C ON C.CATCH_ID = FEC.CATCH_ID
  INNER JOIN TRIP_SURVEY TS ON TS.TRIP_ID = FEC.TRIP_ID
  INNER JOIN SURVEY S ON S.SURVEY_ID = TS.SURVEY_ID
  WHERE C.SPECIES_CODE IN ('044') AND SURVEY_SERIES_ID = 76
  GROUP BY FEC.TRIP_ID,
  FEC.FISHING_EVENT_ID,
  C.SPECIES_CODE
  ORDER BY FEC.FISHING_EVENT_ID")
names(dogfish_catch) <- tolower(names(dogfish_catch))


d <- dplyr::left_join(fe, ye_catch)
d <- dplyr::left_join(d, dogfish_catch, by ="fishing_event_id")

path <- "D:/YE rebuilding plan"
write.csv(d, file.path(path, "ye_inside_dogfish_survey_sets_data.csv"))
