# DÉFINIR LE CONTEXTE DÉCISIONNEL {#sec:decision-context}

Les principales questions qui guident la définition du contexte décisionnel de l’évaluation de la stratégie de gestion sont les suivantes :

* Quelle est la décision exacte à prendre?

* Quel est le délai pour prendre la décision?

* Quels sont les rôles et responsabilités précis des parties concernées? Les parties sont les Sciences, la Gestion des pêches, les Premières Nations, l’industrie, le milieu universitaire et des organisations non gouvernementales.

* Comment la décision finale sera-t-elle prise?

Pour ce plan de rétablissement, il faut décider de la procédure de gestion à utiliser pour déterminer les limites des prises pour la période allant jusqu’au prochain avis disponible sur les prises. 
Le Comité régional d’examen par les pairs devrait prendre la décision finale sur la procédure de gestion à appliquer pour déterminer les futures limites des prises sur une base consensuelle, après avoir examiné le contenu scientifique de l’avis (y compris la structure et le contenu des modèles opérationnels) et tenu compte du rendement relatif des procédures de gestion et des compromis entre les paramètres de rendement.
