#SÉLECTION DES OBJECTIFS ET DES PARAMÈTRES DE RENDEMENT {#sec:objectives-metrics}

Il faut établir des objectifs clairs en matière de gestion et de pêche, ainsi que les paramètres de rendement qui permettent de les évaluer. 
Les objectifs peuvent couvrir un large éventail d’objectifs stratégiques ou législatifs (p. ex., maintenir le stock au-dessus du PRL), d’objectifs économiques (p. ex., maintenir des prises moyennes ou réduire la variabilité des prises) et d’objectifs culturels (p. ex., maintenir l’accès minimal requis au stock ou à des zones de pêche particulières). Dans un scénario de rétablissement, les objectifs de conservation doivent avoir préséance. Cependant, dans un cadre de simulation, il est possible d’examiner des compromis entre la conservation et d’autres objectifs de pêche à court et à long terme, tant que l’objectif principal de conservation est atteint. 
Les objectifs entièrement quantifiés comprennent un paramètre ou une cible, la probabilité souhaitée de réussite et un délai pour atteindre l’objectif (p. ex., la probabilité de maintenir le stock au-dessus du PRL est supérieure à 0,95 [19 fois sur 20] sur 1,5 génération du stock). 
Les paramètres de rendement sont des mesures quantifiées des objectifs. Dans une simulation en boucle fermée, ils sont calculés dans le modèle opérationnel à chaque étape temporelle des projections.

L’objectif initial du plan de rétablissement était de reconstituer le stock au-dessus du PRL sur 80 ans avec une probabilité de réussite de 56 %. Un autre jalon cible était d’atteindre des tendances positives de la biomasse dans chaque période de 10 ans. 
La procédure de gestion convenue pour atteindre ces objectifs était de maintenir le TAC combiné (pêches commerciales, récréatives, ASR, de relevé biologique) à moins de 15 tonnes par année [@ifmp2018].


## OBJECTIFS ET JALONS {#sec:objectives-metrics-obj}

Nous présentons un ensemble d’objectifs améliorés et les paramètres de rendement connexes pour le plan de rétablissement du sébaste aux yeux jaunes des eaux intérieures. 
Les principaux objectifs provisoires de conservation sont guidés par le Cadre de l’approche de précaution [@dfo2006; @dfo2009], le document d’orientation du plan de rétablissement [@dfo2013] et les précédents régionaux [@cox2019; @cox2020]. 
D’autres objectifs liés au rendement des pêches et à la variabilité du rendement annuel des pêches sont fondés sur des précédents dans d’autres analyses de la région du Pacifique du MPO [p. ex., @cox2008a; @forrest2018; @cox2019; @cox2020].


L’objectif de conservation de base proposé est le suivant :

1. Ramener le stock au-dessus du PRL sur 56 ans (1,5 génération) avec une probabilité de réussite d’au moins 95 % [19 fois sur 20].

Nous avons ajusté le délai de rétablissement initial de 80 ans [@ifmp2018] à 56 ans dans la présente analyse, en fonction de la durée de génération estimée pour le sébaste aux yeux jaunes des eaux extérieures [@cox2020], en tenant compte de la directive selon laquelle le rétablissement doit être réalisé dans un délai de 1,5 à 2 durées de génération [@dfo2013]. 
Pour de plus amples renseignements sur la durée de génération, consulter l’annexe \@ref(app:biological-data), section \@ref(sec:generation). 
Nous avons fait passer la probabilité de réussite souhaitée de 56 % à 95 % pour tenir compte de la directive selon laquelle la probabilité de rétablissement doit être élevée, ainsi que des pratiques exemplaires internationales, où les politiques de nombreuses administrations visent à maintenir les stocks au-dessus du PRL avec une probabilité de 90 % à 95 % [18 à 19 fois sur 20] [@sainsbury2008; @mcilgorm2013].


Nous proposons également les objectifs supplémentaires suivants, précisés dans la section \@ref(sec:objectives-metrics-pm):

2. Reconstituer le stock au-dessus du RSS sur 56 ans (1,5 génération).

3. Reconstituer le stock au-dessus du PRL sur 38 ans (1 génération).

4. Les objectifs de conservation ci-dessus étant atteints, maintenir des prises cibles moyennes à court et à long terme.

5. Les objectifs de conservation ci-dessus étant atteints, réduire au minimum la variabilité des prises dans les pêches d’une année à l’autre.

Il convient de noter que nous n’avons pas attribué de probabilités cibles à ces objectifs, car elles sont fournies aux fins de l’évaluation des compromis avec l’objectif 1. 
Toutefois, nous avons éliminé les procédures de gestion qui ne respectaient pas la probabilité minimale de maintenir les prises au-dessus de 10 tonnes à court terme (voir la section \@ref(sec:simulation)).

En plus des objectifs susmentionnés, nous proposons de peaufiner les jalons définis dans le plan de rétablissement initial [@ifmp2018] en ajoutant le texte en italiques comme suit :

6. Atteindre des tendances positives de la biomasse dans chaque période de 10 ans *tant que le stock demeure inférieur au PRL*.

La période de 10 ans indiquée dans les jalons du plan de rétablissement actuel du sébaste aux yeux jaunes des eaux intérieures [@ifmp2018] reflétait une hypothèse selon laquelle le rétablissement hors de la zone critique pourrait être très lent pour ce stock. 
Nous avons ajusté le jalon pour tenir compte de l’hypothèse selon laquelle, une fois que le stock n’est plus dans la zone critique, le jalon ne sera plus nécessaire. 
La directive actuelle sur le rétablissement [@dfo2013] ne prévoit que des objectifs pour faire sortir les stocks de la zone critique, avec des jalons visant à garantir que les progrès sont réalisés pendant le processus de rétablissement. 
Elle mentionne des objectifs à plus long terme pour poursuivre le rétablissement des stocks jusque dans la zone saine, au-dessus du RSS. 
Toutefois, cela est censé se produire après la période du plan de rétablissement et en dehors de la portée de ce dernier [@dfo2013].


## PARAMÈTRES DE RENDEMENT {#sec:objectives-metrics-pm}

Nous proposons les paramètres de rendement suivants pour mesurer les objectifs, où *B* représente la biomasse féconde, RMD le rendement maximal durable, *B*~RMD~ la biomasse féconde à l’équilibre au rendement maximal durable, DG représente la durée d’une génération, et EAMP l’écart absolu moyen des prises ($C$) sur les $n$ années (remarque : *CT* = court terme, *LT* = long terme). 
Nous définissons le PRL et le RSS comme 0,4*B*~RMD~ et 0,8*B*~RMD~, respectivement, en suivant les définitions provisoires du Cadre de l’approche de précaution [@dfo2006], utilisées dans l’évaluation des stocks de 2010 [@yamanaka2011]. 
Dans les simulations en boucle fermée, tous les points de référence et les paramètres de rendement sont calculés dans le modèle opérationnel. 
Les paramètres de rendement bruts sont calculés pour chacune des 100 années de la période de projection et résumés en fonction de la période d’intérêt :

1. **PRL 1,5DG** : P(*B* > 0,4 *B*~RMD~) après 1,5 DG (en 2075, année 56 de la période de projection)
2. **RSS 1,5DG** : P(*B* > 0,8 *B*~RMD~) après 1,5 DG (en 2075, année 56 de la période de projection)
3. **PRL 1DG** : P(*B* > 0,4 *B*~RMD~) après 1 DG (en 2057, année 38 de la période de projection)
4. **CT C10** : P(prises moyennes > 10 tonnes) de 2020 à 2029, années 1 à 10 de la période de projection 
5. **CT C15** : P(prises moyennes > 15 tonnes) de 2020 à 2029, années 1 à 10 de la période de projection
6. **LT C20** : P(prises moyennes > 20 tonnes) après 1 DG (en 2057, année 38 de la période de projection)
7. **CT EAMP** : P(EAMP~2020-2029~ < EAMP~2012-2019~)


Nous avons inclus le paramètre de rendement PRL 1 DG pour nous assurer que les procédures de gestion ne mènent pas le stock à l’effondrement à court terme. 
Nous avons choisi 10 tonnes, 15 tonnes et 20 tonnes comme cibles de prises, qui représentent des niveaux de prises de 5 tonnes inférieurs et supérieurs au TAC actuel de 15 tonnes.

Nous avons calculé EAMP~2020-2029~ comme suit :


$$
\textrm{AADC}_\textrm{2020-2029} = \dfrac{1}{9}\sum_{y=2021}^{2029} \mid C_y - C_{y-1} \mid.
$$

Une période de référence (de 2012 à 2019) a été choisie, car elle marque le début du TAC de 15 tonnes. Nous avons calculé EAMP~2012-2019~ comme suit :

$$
\textrm{AADC}_\textrm{2012-2019} = \dfrac{1}{7}\sum_{y=2013}^{2019} \mid C_y - C_{y-1} \mid.
$$

Lorsque les paramètres de rendement sont calculés sur plusieurs années, il faut prendre soin d’expliquer clairement la façon dont les statistiques sommaires sont calculées. 
@anderson2020gfmp suggéraient provisoirement de calculer les statistiques de rendement sur les répétitions et les années pour toute la période définie pour le paramètre de rendement. 
Nous suivons ce protocole. 
Par exemple, nous avons calculé la moyenne des paramètres des prises à court terme par rapport aux répétitions et aux années 2020 à 2029.

