
# DÉTERMINATION DES PROCÉDURES DE GESTION POSSIBLES {#sec:mp}
@anderson2020gfmp ont examiné toutes les procédures de gestion qui étaient accessibles dans l’outil DLMtool en novembre 2019. 
L’outil DLMtool comprend un ensemble complet de procédures de gestion à données limitées qui formulent différents types de recommandations de gestion, y compris des ajustements au TAC, à l’effort ou à la répartition spatiale des prises ou de l’effort.
@anderson2020gfmp ont exclu certaines procédures de gestion du Cadre des procédures de gestion, car leurs exigences seraient rarement respectées pour les stocks de poisson de fond de la Colombie-Britannique.
Les procédures de gestion exclues étaient celles qui exigeaient une connaissance de l’abondance absolue, des données récentes sur la composition selon l’âge, une connaissance de l’épuisement et une connaissance du taux de variation de la pente (*h*) de la relation stock-recrutement, puisqu’il s’agit probablement de grands axes d’incertitude pour les stocks auxquels ce cadre sera appliqué.
Bien qu’il soit nécessaire d’explorer ces axes d’incertitude dans les modèles opérationnels, la mise en œuvre des procédures de gestion qui exigent la connaissance de ces facteurs nécessiterait de nombreuses hypothèses supplémentaires.
@anderson2020gfmp ont également ajusté certaines des procédures de gestion de l’outil DLMtool afin de tenir compte des types de données accessibles sur le poisson de fond de la Colombie-Britannique (p. ex., relevés biennaux dans plusieurs zones de gestion).

Le Cadre des procédures de gestion ne tient compte que des procédures de gestion qui font des recommandations sur le TAC, parce que la plupart des stocks de poisson de fond sont gérés par des quotas et des TAC.
Un recueil de toutes les procédures de gestion prises en compte dans le Cadre des procédures de gestion est fourni dans @anderson2020gfmp (à l’annexe D).
Les procédures de gestion qui ont été prises en considération pour le plan de rétablissement actuel sont décrites en détail à l’annexe \@ref(app:mps) du présent document.

Nous avons évalué deux principaux types de procédures de gestion : les procédures de gestion empiriques (fondées sur des données) et les procédures de gestion fondées sur des modèles. 
Nous avons également évalué trois procédures de gestion de référence.

L’ensemble complet des procédures de gestion possibles est indiqué dans le tableau \@ref(tab:mps). Voir les descriptions complètes à l’annexe \@ref(app:mps).


## PROCÉDURES DE GESTION EMPIRIQUES

Les procédures de gestion empiriques utilisent les données sur les prises et l’indice de la population.
Elles peuvent être divisées en deux grandes catégories : les procédures de gestion à prises constantes et les procédures de gestion fondées sur des indices.


### Procédures de gestion à prises constantes

Les procédures de gestion à prises constantes établissent les prises recommandées à un niveau fixé, habituellement en fonction des prises récentes ou historiques. 
Les procédures de gestion à prises constantes ne tiennent pas compte de la réaction entre le système de gestion et la population; --- elles font la même recommandation, quelles que soient les tendances de l’indice de population. 
La procédure de gestion actuelle utilisée pour le sébaste aux yeux jaunes des eaux intérieures est une procédure de gestion à prises constantes de 15 tonnes.

Nous avons examiné trois procédures de gestion à prises constantes : 5 tonnes, 10 tonnes et 15 tonnes (annexe \@ref(app:mps), section \@ref(sec:mp-cc)).

### Procédures de gestion fondées sur des indices 

En général, les procédures de gestion fondées sur des indices ajustent le TAC en fonction de l’évolution d’un indice de la population au fil du temps. 
Les procédures de gestion indice-ratio augmentent ou diminuent le TAC en fonction du ratio de l’indice sur deux périodes différentes. 
Les procédures de gestion indice-pente augmentent ou diminuent le TAC en fonction de la pente estimée de l’indice sur une période récente. 
Un troisième type, les procédures de gestion indice-cible, ajuste le TAC en fonction du ratio de l’indice récent et d’une valeur fixée de l’indice cible, d’après une période historique préétablie.
Nous n’avons pas envisagé de procédure de gestion indice-cible ici, car d’autres directives seraient nécessaires pour sélectionner la valeur cible appropriée. 
De plus, pour les plans de rétablissement, l’objectif principal est de ramener le stock au-dessus du PRL.
Toutefois, il est peu probable que le PRL soit un état de stock cible final souhaité.

Nous avons évalué les procédures de gestion fondées sur des indices avec des mises à jour annuelles ou des mises à jour quinquennales (indiquées par « 5u ») avec un TAC fixe entre les mises à jour, c’est-à-dire le dernier TAC recommandé. 
Toutes les procédures de gestion fondées sur des indices ont établi un « plancher » minimum du TAC = 0,5 tonne, qui correspond approximativement à la quantité de prises requise pour pouvoir poursuivre les relevés scientifiques. 
Nous avons inclus les procédures de gestion fondées sur des indices suivantes : Iratio, Islope, GB_slope et IDX, avec diverses configurations (annexe \@ref(app:mps), section \@ref(sec:mp-ibased)).

## PROCÉDURES DE GESTION FONDÉES SUR DES MODÈLES

En plus des procédures de gestion empiriques, nous avons envisagé un modèle de production excédentaire, jumelé à deux règles de contrôle des prises de rechange. 
Nous avons évalué deux fréquences d’évaluation (5 et 10 ans), avec un TAC fixe entre les évaluations (annexe \@ref(app:mps), section \@ref(sec:mp-sp)). 
Nous avons utilisé le modèle de production excédentaire codé dans MSEtool [@huynh_msetool_2019] et fondé sur @fletcher1978 [voir l’annexe D dans @anderson2020gfmp].

Les règles de contrôle des prises de rechange (figure \@ref(fig:mp-hcrs)) étaient caractérisées par :

1. 80 %B~RMD~ et 40 %B~RMD~ comme RSS et PRL, respectivement;
2. 40 %B~0~ et 10 %B~0~ comme RSS et PRL, respectivement.

## PROCÉDURES DE GESTION DE RÉFÉRENCE

En plus des procédures de gestion empiriques et fondées sur des modèles possibles, nous avons inclus les procédures de gestion de référence suivantes :

1. Aucune pêche (APref)
2. Pêche à *F*/*F*~RMD~ (FRMDref)
3. Pêche à 0,75 *F*/*F*~RMD~ (FRMDref75)

Le but des procédures de gestion de référence n’est pas d’explorer des stratégies de gestion viables, mais de limiter l’éventail du rendement attendu ou possible et de mettre en contexte si les différences entre les statistiques sur le rendement des procédures de gestion sont significatives [@punt2016]. 
Par exemple, la procédure de gestion de référence « aucune pêche » fournit de l’information sur les niveaux de stocks maximaux possibles et le taux de rétablissement maximal possible dans un scénario de rétablissement.

\clearpage

```{r mps, results='asis'}
mp <- readr::read_csv(here("mse",  "mp.txt"), comment = "#")
csasdown::csas_table(mp, caption = "Procédures de gestion possibles. \"5u\" et \"10u\" font référence à des intervalles de cinq et dix ans entre les mises à jour; les autres procédures de gestion ont été appliquées chaque année. Les autres numéros font référence aux configurations des procédures de gestion.", col_names = c("Procédure de gestion", "Type de procédure de gestion"))
```

\clearpage
