# DISCUSSION {#sec:discussion}

Nous avons appliqué un nouveau Cadre des procédures de gestion pour les poissons de fond du Pacifique [@anderson2020gfmp] afin d’évaluer la capacité des autres procédures de gestion à atteindre les objectifs de rétablissement pour le sébaste aux yeux jaunes des eaux intérieures. 
Il s’agit de la première application du Cadre des procédures de gestion à des fins décisionnelles.

Nous avons évalué le rendement de 31 procédures de gestion à données limitées (et de trois procédures de gestion de référence) en ce qui a trait à l’atteinte des objectifs décrits dans la section 3. 
Nous avons éliminé les procédures de gestion qui ne satisfaisaient pas aux deux critères PRL 1,5DG > 0,9 et CT C10 > 0,50 dans les scénarios de l’ensemble de référence de modèles opérationnels, et il est resté 
`r gfutilities::number_to_word(length(mp_sat))` procédures de gestion (`r gfutilities::commify(sort(mp_sat))`).
Toutes les procédures de gestion restantes atteignaient les paramètres de conservation PRL 1,5DG, SSR 1,5DG et PRL 1DG avec une probabilité supérieure à 0,98 (49 fois sur 50) dans les quatre scénarios de l’ensemble de référence de modèles opérationnels, surtout qu’aucun des modèles opérationnels de l’ensemble de référence n’estimait que le stock serait dans la zone critique en 2020---le début de la période de projection. 
Dans les deux scénarios de l’ensemble de robustesse de modèles opérationnels, le scénario de modèle opérationnel (B), qui simulait une plus grande variabilité dans le futur relevé à la palangre sur fond dur, a donné des résultats semblables à ceux des scénarios de l’ensemble de référence de modèles opérationnels. 
Cependant, dans le scénario de modèle opérationnel (A), le scénario M faible, les probabilités de respecter le paramètre de rendement PRL 1,5DG variaient de 0,75 (75 fois sur 100) à 0,9 (neuf fois sur 10), la procédure de gestion actuelle (CC_15t) ayant la probabilité la plus faible dans cette fourchette.

Alors que les directives du plan de rétablissement [@dfo2013] ne décrivent que les objectifs liés au rétablissement, nous avons également évalué le rendement des procédures de gestion pour trois objectifs de prises moyennes et un objectif de variabilité des prises. 
Les procédures de gestion CC_10t et CC_15t, par définition, respectaient leurs paramètres de rendement CT C10 et CT C15 respectifs. 
Un certain contraste est apparu entre les procédures de gestion Islope dans l’ensemble de référence pour CT C10 et CT C15 selon la configuration de la procédure de gestion et le scénario de modèle opérationnel. 
Les scénarios de l’ensemble de robustesse de modèles opérationnels produisaient généralement des probabilités plus faibles de respecter le paramètre CT C10.

Nous présentons un certain nombre de visualisations pour illustrer les compromis entre les objectifs de conservation et de prises [voir aussi @anderson2020gfmp]. 
Ces visualisations illustrent les compromis sous forme de différents tableaux et de graphiques, destinés à faciliter le processus de sélection de la procédure de gestion finale. 
Étant donné que toutes les procédures de gestion atteignaient l’objectif du PRL 1,5DG dans les scénarios de l’ensemble de référence de modèles opérationnels, il n’y avait pas de compromis important entre les objectifs de conservation et les objectifs de prises. 
Parmi les deux scénarios de l’ensemble de robustesse de modèles opérationnels, les compromis étaient les plus évidents dans le scénario de M faible, où la probabilité d’atteindre l’objectif du PRL 1,5DG diminuait à mesure que la probabilité d’atteindre CT C10 augmentait.

Nous avons constaté que les visualisations des diagrammes en radar étaient difficiles à interpréter. 
Bien que ces diagrammes puissent être utiles pour visualiser rapidement plusieurs compromis et qu’ils aient été recommandés pour la visualisation des résultats de l’évaluation de la stratégie de gestion [@punt2017], ils deviennent plus difficiles à interpréter à mesure que l’on ajoute d’autres paramètres (« rayons »). 
Ils sont également très sensibles à l’ordre dans lequel les paramètres sont placés, et il a été démontré qu’ils sont moins interprétables que les graphiques cartésiens [@diehl2010; @feldman2013; @albo2016]. Nous avons présenté des diagrammes en radar ici pour évaluer l’intérêt des participants au processus régional d’examen par les pairs et leur demander leurs commentaires sur la question de savoir s’il faut les inclure dans les futures applications du Cadre des procédures de gestion.


## MORTALITÉ NATURELLE {#sec:discussion-m}

L’objectif de l’ensemble de robustesse est d’explorer les formulations des modèles opérationnels qui représentent d’autres hypothèses que celles de l’ensemble de référence [@rademeyer2007; @punt2016]. 
Les procédures de gestion possibles devraient donner de bons résultats dans les scénarios de référence et de robustesse de modèles opérationnels [@rademeyer2007]. 
Dans notre étude, les deux scénarios de l’ensemble de robustesse de modèles opérationnels ont donné des résultats différents des scénarios de l’ensemble de référence de modèles opérationnels, en particulier le scénario de modèle opérationnel (A). 
Ce scénario de faible mortalité/faible productivité ($M \sim \textrm{Lognormal}(0,025, 0,2)$) était le seul où la biomasse médiane était estimée se trouver dans la zone critique au début de la période de projection. 
Pour tous les autres scénarios de modèles opérationnels, nous avons échantillonné selon une distribution de probabilités pour *M* avec une moyenne de 0,045 y^-1^, qui correspondait à celle utilisée dans l’évaluation du stock précédente [@yamanaka2011].

Le taux de mortalité naturelle des populations de poissons est l’un des paramètres les plus importants, mais les plus difficiles à estimer. 
De nombreuses méthodes ont été élaborées pour estimer *M* à partir des paramètres du cycle biologique accessibles. 
Les paramètres du sébaste aux yeux jaunes des eaux intérieures ont été saisis dans une [application](http://barefootecologist.com.au/shiny_m.html) mise au point par des scientifiques de la NOAA, qui permet d’estimer *M* à l’aide de diverses méthodes empiriques publiées. Les estimations de *M* variaient de 0,03 à 0,17, selon la méthode empirique. D’autres évaluations du sébaste aux yeux jaunes ont utilisé des valeurs plus faibles pour *M*, plus proches ou plus basses que celles utilisées dans le scénario de modèle opérationnel (A) (moyenne de 0,025 y^-1^). 
Par exemple, le récent plan de rétablissement du stock de sébaste aux yeux jaunes des eaux extérieures a estimé les valeurs médianes pour *M* entre 0,031 *y*^-1^ et 0,044 *y*^-1^, selon le modèle opérationnel [@cox2020]. 
L’évaluation et le rapport de situation de 2008 du COSEPAC pour les stocks de sébaste aux yeux jaunes des eaux intérieures et extérieures [@cosewic2008] ont utilisé une valeur de *M* = 0,02 *y*^-1^, citant l’évaluation de 2001 du stock des eaux intérieures [@yamanaka2001]. 
De même, les évaluations du stock de sébaste aux yeux jaunes du sud du golfe d’Alaska ont utilisé une valeur de *M* = 0,02 *y*^-1^ [@wood2019].

Les taux de mortalité naturelle ont probablement varié au fil du temps, en raison des changements dans les populations de prédateurs dans le détroit de Georgie. 
Le sébaste aux yeux jaunes occupe une position trophique relativement élevée [@olson2020] : l’otarie de Steller, l’épaulard (*Orcinus orca*) et le saumon chinook (*Oncorhynchus tshawytscha*) sont ses seuls prédateurs inscrits dans une grande base de données sur les interactions prédateur-proie (base de données assemblée pour @dunne2016; @szoboszlai2015). 
Les populations des trois espèces prédatrices ont beaucoup fluctué au cours du dernier siècle.
L’abondance de l’otarie de Steller a été considérablement réduite en raison de la chasse et du contrôle des prédateurs, mais elle s’est maintenant rétablie à des niveaux historiques [@olesiuk2018; voir l’annexe F]. 
La population résidente d’épaulard du sud est en voie de disparition et la population résidente du nord est menacée [@cosewic2008b]. La cause du déclin des deux populations est attribuée au déclin de l’abondance du saumon chinook [@ford2010]. 
On a également observé une prédation sur le sébaste aux yeux jaunes par le flétan du Pacifique dans le golfe d’Alaska [@livingston2017]; toutefois, le flétan du Pacifique n’est pas très abondant dans les eaux intérieures (voir les données du relevé de 2018 de la CIFP dans @anderson2019synopsis). 
La morue-lingue est probablement un prédateur des sébastes aux yeux jaunes juvéniles, car c’est un prédateur connu des espèces de sébastes. 
Cependant, les études des contenus stomacaux ne permettent souvent pas d’identifier les espèces de sébastes au-delà de « sébaste non identifié » (@beaudreau2007, @livingston2017). 
La population de morue-lingue dans le détroit de Georgie a également beaucoup décliné et on pensait que la pêche l’avait fait chuter à 2 % des niveaux historiques en 1990, mais elle a augmenté depuis [@logan2005; @holt2016]. 
Des projets pourraient étudier les effets de la mortalité naturelle variable dans le temps sur le sébaste aux yeux jaunes des eaux intérieures.

## AIRES DE CONSERVATION DU SÉBASTE {#sec:discussion-rca}

Dans le cadre de la stratégie de conservation du sébaste, 164 aires de conservation du sébaste (ACS), dans lesquelles les pêches ciblant le sébaste ou le capturant comme prises accessoires sont interdites, ont été établies dans les eaux de la Colombie-Britannique entre 2004 et 2006 [@yamanaka2010]. 
Il y a 130 ACS dans la zone 4B (figure \@ref(fig:map-4B)) qui protègent environ 267 kilomètres carrés d’habitat du sébaste, soit 22 % de l’habitat disponible dans les eaux intérieures [@haggarty2018]. 
Bien que les ACS aient été établies comme une mesure visant à aider à reconstituer les populations de sébaste [@yamanaka2010], la présente analyse ne tient pas compte des effets possibles des fermetures.
 Les relevés par véhicule sous-marin téléguidé effectués dans les ACS dans les eaux intérieures ont révélé qu’il n’y avait pas de différence dans l’abondance ou la taille du sébaste aux yeux jaunes dans les ACS au moment de l’étude (de 3 à 7 ans après la mise en place des aires) [@haggarty2016b]. 
Compte tenu de l’âge tardif à la maturité et de la longévité du sébaste, il faudra sans doute plus de 20 ans pour que les populations affichent des réactions aux zones fermées [@starr2015]. 
Les ACS dans les eaux intérieures étant maintenant en place depuis 14 à 16 ans, nous pourrions commencer à y trouver bientôt des sébastes plus grands et en plus forte densité. 
Le MPO, en partenariat avec des biologistes du Washington Department of Fish and Wildlife (WDFW) et de la National Ocean and Atmospheric Administration (NOAA), a entrepris un relevé par véhicule sous-marin téléguidé de plusieurs ACS dans le détroit de Georgie à l’automne 2018, à bord du NGCC Vector. 
Cependant, les résultats de ce relevé n’ont pas été publiés à temps pour être inclus dans ce projet. 

## ÉTAT DU STOCK {#sec:discussion-status}


Le plan de rétablissement du stock de sébaste aux yeux jaunes des eaux intérieures a été déclenché par l’évaluation du stock de 2010 [@yamanaka2011], qui a estimé qu’il y avait une probabilité élevée que le stock soit inférieur au PRL. 
De tous les modèles opérationnels des ensembles de référence et de robustesse explorés dans notre analyse, seul le scénario de modèle opérationnel (A), M faible, a estimé que la médiane de la biomasse féconde serait inférieure au PRL en 2010. 
Dans tous les scénarios de modèles opérationnels, les écarts de recrutement sur l’échelle logarithmique ont commencé à augmenter après 2000, bien qu'ils soient toujours en deçà de zéro, suivant probablement les légères augmentations de l’indice du relevé à la palangre sur fond dur pendant cette période. 
L’évaluation de 2010 a utilisé un modèle de production excédentaire, avec des hypothèses structurelles fondamentalement différentes de l’analyse de réduction du stock utilisée pour le conditionnement des modèles opérationnels dans notre analyse. 
À titre de vérification, nous avons ajusté un modèle de production excédentaire, semblable à celui utilisé par @yamanaka2011, et avons obtenu des estimations de la biomasse et de l’état du stock beaucoup plus faibles que celles des modèles opérationnels d’analyse de rétablissement du stock de l’ensemble de référence. 
De plus, dans le modèle de production excédentaire, l’estimation de *B*~RMD~ était plus élevée que notre scénario de modèle opérationnel (1) et l’estimation de *F*~RMD~ inférieure à celle des modèles d’analyse de réduction du stock de l’ensemble de référence, ce qui indique une productivité plus faible dans le modèle de production excédentaire. 
La productivité et la biomasse estimées plus faibles et une *B*~RMD~ plus élevée dans le modèle de production excédentaire donneraient une évaluation plus pessimiste de l’état du stock. 
L’exercice d’ajustement du modèle de production excédentaire donne à penser que la structure du modèle, plus que l’ajout de dix années de nouvelles données depuis la dernière évaluation, était un facteur important qui a contribué aux différentes perceptions de l’état du stock entre les modèles opérationnels actuels et l’évaluation précédente.

Dans une évaluation récente du stock de sébaste aux yeux jaunes des eaux extérieures, @cox2020 ont relevé des différences semblables entre leurs modèles opérationnels structurés selon l’âge, qui estimaient que l’état du stock était supérieur au PRL, et l’évaluation fondée sur la production excédentaire de 2014 [@yamanaka2018yelloweyeoutside], selon laquelle le stock était inférieur au PRL, déclenchant un plan de rétablissement. 
@cox2020 ont remarqué que les différences structurelles entre les modèles de production excédentaire et les modèles structurés selon l’âge devraient produire des résultats différents, surtout en raison des différences dans la formulation de la productivité. 
Nous avons été en mesure d’imiter les estimations de l’état du stock de @yamanaka2011 en forçant une productivité plus faible du stock dans le scénario de modèle opérationnel (A), même si la valeur moyenne de *M* utilisée dans le scénario de modèle opérationnel (A) était inférieure à celle utilisée par @yamanaka2011 pour calculer la valeur a priori de la productivité pour leur modèle de production excédentaire. 
@cox2020 ont souligné que les modèles structurés selon l’âge prévoient des retards du recrutement dans les pêches, les relevés et le stock reproducteur, des caractéristiques qui peuvent favoriser la résilience et qui sont plus réalistes pour une espèce longévive comme le sébaste aux yeux jaunes. 
Ces différences sont contrôlées par la sélectivité de la pêche selon l’âge, la sélectivité du relevé selon l’âge et la maturité selon l’âge, respectivement, dans les modèles structurés selon l’âge et peuvent être trop simplifiées dans les modèles de production excédentaire agrégés. 
Notre scénario de modèle opérationnel (4), dans lequel nous avons estimé la sélectivité du relevé selon l’âge, a produit des estimations plus faibles de l’état du stock, ce qui signifie que les hypothèses au sujet de la sélectivité ont contribué aux perceptions de l’état du stock (voir la section \@ref(sec:discussion-uncertainties-selectivity)), fort probablement en raison des impacts sur d’autres estimations de paramètres comme *R*~0~ et l’autocorrélation dans le recrutement. 
@cox2020 ont également remarqué que leurs procédures de gestion fondées sur la production excédentaire avaient tendance à sous-estimer la biomasse, ce que nous avons aussi constaté dans la présente étude, où les procédures de gestion de la production excédentaire n’ont pas généré de prises dans la première décennie des projections.

Malgré les différences de perception de l’état du stock entre certains de nos modèles opérationnels, et entre cette évaluation et la précédente, nous remarquons que le Cadre des procédures de gestion fournit une méthode d’intégration des principales incertitudes dans l’état du stock et les points de référence (voir la section \@ref(sec:discussion-implicit)) qui sont prévalentes pour ce stock. 
En particulier, l’inclusion du scénario de modèle opérationnel (A) dans l’ensemble de robustesse offre aux décideurs un autre point de vue sur l’état du stock et le rendement des procédures de gestion. Dans de tels cas, où les données accessibles ne sont pas suffisantes pour résoudre les différentes estimations de l’état du stock, on peut recourir à une approche du « poids de la preuve » pour prendre des décisions de gestion [@kronlund2020]. Une approche fondée sur le poids de la preuve tient compte des contributions combinées des différentes études (ensemble de la preuve) et fait appel au jugement d’experts pour attribuer des pondérations à chaque source de données (études individuelles ou modèles opérationnels). 

## PRINCIPALES INCERTITUDES {#sec:discussion-uncertainties}

### Sélectivité {#sec:discussion-uncertainties-selectivity}
La sélectivité était une source majeure d’incertitude dans nos modèles opérationnels. 
Il n’existe aucune donnée sur la composition selon l’âge pour les pêches commerciales ou récréatives, et aucune donnée du relevé sur l’aiguillat commun. 
Nous avons donc fixé la sélectivité pour tous ces engins. 
Les sélectivités pour les pêches commerciales et récréatives ont été établies de façon à correspondre à celles déclarées pour le stock des eaux extérieures [@cox2020], et nous avons fixé la sélectivité dans le relevé sur l’aiguillat commun pour refléter la valeur utilisée pour le relevé à la palangre sur fond dur. 
Toutefois, il a été noté au cours du processus de rétablissement du sébaste aux yeux jaunes des eaux extérieures qu’il faudrait effectuer des échantillonnages biologiques supplémentaires pour étayer la sélectivité dans les pêches commerciales, récréatives et à des fins ASR [@dfo2020], et cette recommandation s’applique également à la population des eaux intérieures. Des données biologiques complètes, y compris des otolithes de sébaste aux yeux jaunes, ont été recueillies pour la première fois pendant le relevé sur l’aiguillat commun en 2019. 
Même si les données sur l’âge n’étaient pas encore accessibles pour ce travail, elles pourraient orienter la sélectivité dans le relevé sur l’aiguillat commun pour les travaux futurs. 
Nous avons également lancé en août 2019 un projet pour comparer les engins des relevés à la palangre sur fond dur et sur l’aiguillat commun en pêchant à certains des sites du relevé sur l’aiguillat commun avec les engins des deux relevés. Ces données peuvent également guider la comparabilité des deux relevés. 

Les données sur la composition selon l’âge tirées des relevés dans la zone 4B étaient rares et n’ont été recueillies que ces dernières années. 
Les premières tentatives d’estimation de la sélectivité dans le relevé à la palangre sur fond dur (associées à une pondération égale entre ce relevé et celui sur l’aiguillat commun) ont donné des estimations invraisemblables de l’âge à la pleine sélectivité et une forte tendance rétrospective dans les estimations de la biomasse. 
Par conséquent, nous avons fixé à 22 *y* l’âge à la pleine sélectivité et nous avons augmenté la pondération de la composante de vraisemblance du relevé sur l’aiguillat commun, ce qui a nettement amélioré le comportement rétrospectif. 
Pour séparer les effets de l’augmentation de la pondération du relevé sur l’aiguillat commun de la détermination de la sélectivité du relevé à la palangre sur fond dur, nous avons estimé cette dernière dans le scénario de modèle opérationnel (4), ce qui a légèrement modifié la perception de l’état du stock.

Nous aurions pu explorer d’autres hypothèses de sélectivité fixes, mais nous pensons avoir utilisé les valeurs les plus plausibles et, pour le relevé à la palangre sur fond dur, nous avons inclus un autre scénario de modèle opérationnel dans l’ensemble de référence. 
Les applications futures du Cadre des procédures de gestion pour ce stock pourraient examiner d’autres scénarios de modèles opérationnels de sélectivité.


### Prises historiques {#sec:discussion-uncertainties-catch}

L’autre grande source d’incertitude dans nos analyses est l’ampleur des prises commerciales et récréatives historiques. L’incertitude concernant les prises commerciales vient du fait qu’avant 1950, les sébastes autres que le sébaste à longue mâchoire étaient déclarés dans une catégorie agrégée; l’ampleur des prises non déclarées de 1986 à 2005 constitue également une grande incertitude.
@haigh2011 ont reconstitué les données sur les prises historiques jusqu’en 2005 et tenté de séparer le sébaste aux yeux jaunes de la catégorie agrégée des sébastes et de tenir compte des poissons rejetés. 
Les prises reconstituées ont été utilisées dans l’évaluation précédente du stock [@yamanaka2011].
Malgré une certaine controverse au sujet des données reconstituées sur les prises, pour le stock de sébaste des eaux extérieures comme pour celui des eaux intérieures, la réévaluation de la reconstitution était hors de la portée de ce travail et demeure la meilleure série chronologique accessible des prises historiques. 
Nous avons donc repris la même approche que @yamanaka2011 pour reconstituer les données historiques sur les prises récréatives et estimer les prises récréatives actuelles. 
Nous avons évalué l’effet du doublement des données sur les prises nominales de 1986 à 2005 dans le scénario de modèle opérationnel (2), mais le rendement des procédures de gestion n’était pas sensiblement différent des autres scénarios de l’ensemble de référence de modèles opérationnels.

Nous nous sommes écartés de @yamanaka2011 dans notre traitement des prises à des fins ASR . Ils ont appliqué un algorithme pour estimer explicitement les prises à des fins ASR , en se fondant sur des hypothèses au sujet des taux de consommation. 
Après avoir discuté avec des ichtyobiologistes qui travaillent avec les Premières Nations locales dans les parties nord et sud de la zone 4B, nous avons choisi d’inclure les prises à des fins ASR  avec les prises commerciales dans la partie nord, la plupart des prises de sébaste étant capturées en vertu de permis de double pêche et étant donc incluses dans les bases de données sur les prises commerciales du MPO. 
Nous avons choisi de supposer que les prises à des fins ASR  dans la région du sud étaient comptabilisées dans les prises récréatives, parce que la plupart des prises de sébaste sont effectuées à partir de petits bateaux, de sorte que l’effort, du moins, est probablement déjà compté par les survols du MPO. 
Nous sommes conscients des grandes incertitudes entourant les prises à des fins ASR . 
Les applications futures du Cadre des procédures de gestion de ce stock bénéficieraient d’un travail de collaboration plus détaillé avec les Premières Nations pour quantifier les prises à des fins ASR  contemporaines et historiques dans la zone 4B.


## CONNAISSANCE IMPLICITE ET EXPLICITE DES POINTS DE RÉFÉRENCE LIMITES {#sec:discussion-implicit}

Ce Cadre des procédures de gestion et tous les processus d’évaluation de la stratégie de gestion diffèrent des évaluations classiques des stocks de par la façon dont les avis scientifiques sont fournis [@anderson2020gfmp]. 
Dans la plupart des évaluations des stocks de poisson de fond de la Colombie-Britannique [p. ex., @yamanaka2011; @starr2017; @forrest2019], les avis sur les prises sont présentés sous forme de tableaux de décision, où les probabilités de dépassement des points de référence (p. ex., la probabilité que les stocks tombent en deçà du PRL) sont présentées pour un éventail de futurs niveaux de TAC possibles. 
Cette approche dépend de la déclaration explicite des points de référence et de l’estimation de l’état des stocks. 
Une fois qu’un tableau de décision a été produit, il incombe aux décideurs de choisir un futur TAC en fonction des probabilités présentées, en tenant compte d’autres facteurs comme les besoins économiques de la pêche et un certain niveau de tolérance au risque. 
Dans ce processus, la prise en compte du risque se fait à l’étape finale du processus décisionnel et n'est pas toujours transparente ou liée à des objectifs convenus à l’avance.

Les cadres de procédures de gestion diffèrent des évaluations conventionnelles de deux façons principales : 1) les points de référence et l’état des stocks ne sont pas explicitement déclarés; 2) les objectifs liés à la probabilité de dépasser les points de référence doivent être convenus au début du processus (l’étape 2 des pratiques exemplaires). 
Les points de référence et l’état des stocks font donc toujours partie intégrante du cadre, mais ils sont calculés dans les modèles opérationnels et intégrés dans les paramètres de rendement. 
Il est essentiel de s’entendre sur le risque acceptable (p. ex., les probabilités acceptables de dépassement des points de référence) au début du processus afin de pouvoir établir les paramètres de rendement et les critères de satisfaction.

Pour de nombreux stocks, en particulier les stocks à données limitées, il n’est pas possible d’en estimer de façon fiable les points de référence biologiques ou l’état. 
Des cadres de procédures de gestion comme celui-ci peuvent être particulièrement importants pour ces stocks. 
Le Cadre pour la pêche durable et les dispositions relatives aux stocks de poissons de la *Loi sur les pêches* exigent que les stocks de poissons soient maintenus à des niveaux durables, et en particulier au-dessus du PRL. 
Ce cadre préserve implicitement l’intention de ces politiques bien que les points de référence et l’état du stock ne soient pas explicitement mis en évidence.

## FRÉQUENCE ET DÉCLENCHEURS DES RÉÉVALUATIONS {#sec:discussion-triggers}

En général, l’objectif d’un cadre de procédures de gestion est de déterminer et de choisir une procédure de gestion solide qui peut être laissée en place pendant une période convenue. 
Il est également recommandé d’effectuer des vérifications provisoires entre les évaluations pour s’assurer que les procédures de gestion choisies fonctionnent comme prévu. 
En plus des étapes des pratiques exemplaires de l’évaluation de la stratégie de gestion, @carruthers2018 décrivent une étape d’évaluation finale, où le rendement de la procédure de gestion choisie est examiné officiellement une fois qu’elle a été mise en œuvre. 
Les écarts par rapport au rendement attendu d’une procédure de gestion ont été qualifiés de « circonstances exceptionnelles ». 
Cela peut se produire lorsque la dynamique du système observée se situe en dehors de l’éventail des scénarios de modèles opérationnels précisés dans les modèles opérationnels pour lesquels la procédure de gestion s’est avérée solide [@butterworth2008].

La preuve de circonstances exceptionnelles, survenant dans l’intervalle recommandé entre les évaluations, déclencherait un examen des modèles opérationnels et de la procédure de gestion, ce qui pourrait entraîner un nouveau modèle opérationnel ou un ajustement de la procédure de gestion choisie [@carruthers_hordyk_2018]. 
Ces auteurs donnent plusieurs exemples d’évaluations de la stratégie de gestion pour lesquelles des protocoles officiels de détection de circonstances exceptionnelles ont été établis. 
En général, les protocoles officiels comprennent la surveillance de l’indice de la biomasse, des prises et d’autres types de données, comme les données sur la composition selon l’âge, et la comparaison des observations aux prévisions du modèle opérationnel. 
L’indice de l’abondance observé sortant de l’intervalle de confiance de 90 % de l’indice projeté par le modèle opérationnel est un exemple de déclencheur d’une réévaluation. 
Voir d’autres recommandations sur les procédures d’évaluation officielles dans @carruthers_hordyk_2018. 
Les procédures d’évaluation informelles, sous la forme de commentaires des intervenants ou de comparaison visuelle des données observées par rapport aux données projetées, peuvent également permettre de détecter des circonstances exceptionnelles [p. ex. @cox2008a].

Parmi les procédures de gestion satisfaisantes dans les analyses actuelles, certaines sont à prises constantes et d’autres sont des procédures de gestion Islope annuelles. Toutes les procédures de gestion fondées sur des indices ont également été évaluées tous les cinq ans. Toutes ces procédures de gestion satisfaisaient aux critères du PRL 1,5DG, mais aucune ne répondait aux critères de CT C10. 
C’est pourquoi nous recommandons des mises à jour annuelles si une procédure de gestion fondée sur des indices est sélectionnée. 
Conformément aux directives pour les plans de rétablissement au Canada [@dfo2013], nous recommandons de réévaluer le rendement de la procédure de gestion choisie au moins tous les trois ans.

# REMERCIEMENTS

Nous remercions Adam Keizer et Maureen Finn (Groupe de gestion du poisson de fond), ainsi que Roger Kanno (coordonnateur du Cadre pour la pêche durable) pour les discussions et les conseils utiles concernant les objectifs du plan de rétablissement.

Nous sommes très reconnaissants à Bob Bocking, Cheri Ayers et Christa Rusel, experts-conseils en pêches qui travaillent avec les Premières Nations locales, et à Mark Fetterly, Aleta Rushton et Patrik Zetterberg du MPO, qui nous ont donné des conseils très utiles au sujet des prises à des fins ASR .

Ross Claytor et Dwayne Lepitzki, du COSEPAC, nous ont fourni des conseils précieux sur l’élaboration des paramètres de rendement qui seront utilisés pour les évaluations du COSEPAC. 

Strahan Tucker et l’équipe responsable des pinnipèdes au sein du MPO ont fourni des données sur l’abondance des pinnipèdes et les taux de consommation de sébaste. Spencer Wood (The Natural Capital Project, Université Stanford) a fait une recherche dans la grande base de données sur les prédateurs et les proies de l’université pour nous.

Rowan Haigh nous a apporté ses conseils sur la reconstitution des prises historiques.

Nous remercions Tom Carruthers et Adrian Hordyk (Université de la Colombie-Britannique) pour leurs recommandations précoces sur ce plan de rétablissement et de leur enthousiasme à ajouter de nouvelles fonctions au logiciel DLMtool sur demande.

Enfin, nous remercions Dayv Lowry (WDFW) et Kendra Holt (MPO) pour leurs commentaires édifiants qui ont grandement amélioré le document de travail.

