\newpage

# PROCÉDURES DE GESTION À DONNÉES LIMITÉES {#app:mps}

Nous présentons ici les procédures de gestion qui ont été évaluées dans le contexte de la présente étude. Voir la liste complète des procédures de gestion possibles dans le Cadre des procédures de gestion de @anderson2020gfmp.

## PROCÉDURES DE GESTION À PRISES CONSTANTES {#sec:mp-cc}

Nous avons évalué trois procédures de gestion à prises constantes : 

- CC_5t : Prises annuelles constantes de 5 tonnes
- CC_10t : Prises annuelles constantes de 10 tonnes
- CC_15t : Prises annuelles constantes de 15 tonnes

## PROCÉDURES DE GESTION FONDÉES SUR DES INDICES {#sec:mp-ibased}

### Procédures de gestion indice-ratio {#sec:mp-iratio}

Les procédures de gestion indice-ratio fondent leur recommandation de TAC pour l’année $y$ sur les prises de l’année précédente $C_{y-1}$ multipliées par le ratio de l’indice moyen de la population sur une période récente (p. ex., les deux dernières années) par rapport à l’indice moyen de la population sur une courte période précédente. L’indice de la population de référence est ainsi une moyenne de fenêtre mobile.

Le TAC est calculé comme suit :

$$
\textrm{TAC}_y = \alpha C_{y-1},
$$

où, par exemple,

$$
\alpha =
\left. \frac{I_{y-1} + I_{y-2}} {2} \middle/
\frac{I_{y-3} + I_{y-4} + I_{y-5}} {3} \right. ,
$$

où $\alpha$ est le ratio de l’indice moyen des deux dernières années et de l’indice moyen des trois à cinq années précédant l’année en cours.

Nous avons évalué deux configurations des procédures de gestion indice-ratio, qui diffèrent de par les périodes utilisées pour calculer $\alpha$, appliquées annuellement :

- Iratio_23 : ratio des deux dernières années par rapport aux trois années précédentes

- Iratio_55 : ratio des cinq dernières années par rapport aux cinq années précédentes

Nous avons également évalué les deux mêmes configurations, appliquées tous les cinq ans :

- Iratio_23_5u : même que Iratio_23

- Iratio_55_5u : même que Iratio_23

### Procédures de gestion indice-pente {#sec:mp-islope}

Les procédures de gestion indice-pente ajustent une régression linéaire des données de l’indice de la population comparées au temps et produisent une recommandation de prises fondée sur la pente de la régression. 
Elles sont étroitement liées aux procédures de gestion indice-ratio. 
Nous décrivons ici trois grandes « familles » de procédures de gestion indice-pente.

#### GB_slope : Pente de l’indice de Geromont et Butterworth {#sec:mp-gb-slope}

Cette procédure de gestion ajuste le TAC en fonction des prises antérieures et de la tendance d’un indice de l’abondance relative pour viser des taux de prises relativement stables [@geromont2015].
Le TAC est calculé comme suit :

$$
\textrm{TAC}_y= C_{y-1}(1+\lambda \beta_I),
$$

où $C_{y-1}$ est les prises de l’année précédente, $\beta_I$ est la pente d’une régression linéaire de l’indice de l’abondance ln au cours des $n$ années précédentes (valeur par défaut de $n = 5$), et $\lambda$ est un paramètre de contrôle entre 0 et 1 qui ajuste la rapidité de l’ajustement du TAC en fonction de la pente de l’indice. La valeur $\lambda$ par défaut est 1 dans l’outil DLMtool.
Le TAC est assujetti aux conditions suivantes qui limitent le taux auquel il peut être ajusté à la hausse ou à la baisse :

- si le TAC suivant > 1,2 les dernières prises, alors le TAC = 1,2 $\times$ les dernières prises
- si le TAC suivant < 0,8 les dernières prises, alors le TAC = 0,8 $\times$ les dernières prises.

Nous avons évalué trois configurations de GB_slope, chacune appliquée annuellement :

- GB_slope_lambda1 : $\lambda = 1$ et $\beta_I$ est calculé à partir de l’indice des cinq années précédentes

- GB_slope_lambda05 : $\lambda = 0,5$ et $\beta_I$ est calculé à partir des cinq années précédentes 

- GB_slope_yrs10 : $\lambda = 1$ et $\beta_I$ est calculé à partir des 10 années précédentes

Nous avons également évalué les trois mêmes configurations, appliquées tous les cinq ans :

- GB_slope_lambda1_5u

- GB_slope_lambda05_5u

- GB_slope_yrs10_5u

Des illustrations des procédures de gestion GB_slope sont fournies dans @anderson2020gfmp (leur annexe D).

#### Islope : Suivi de la pente de l’indice {#sec:mp-islope-track}

Ces procédures de gestion ajustent progressivement le TAC pour tenter de maintenir un indice de l’abondance relative constant. 
Les procédures de gestion sont semblables à "GB_slope" avec l’ajout d’un paramètre qui détermine le TAC pour la première année de projection ($\textrm{TAC}^*$) et différents choix du paramètre $\lambda$.
Le TAC est calculé comme suit :

$$
\textrm{TAC}_y = \textrm{TAC}^*(1+\lambda \beta_I),
$$

où, la première année de projection, $\textrm{TAC}^*$ est $(1-x)$ multiplié par les prises moyennes des cinq dernières années historiques.
Nous avons établi $x = 0$ pour toutes les configurations de la procédure de gestion Islope.
Les années suivantes, $\textrm{TAC}^*$ est le TAC de l’année précédente.
Encore une fois, $\lambda$ est un paramètre de gain ou de lissage, et $\beta_I$ est la pente de l’indice d’abondance ln les dernières $n$ années.

Pour ce qui est des procédures de gestion GB_slope, nous avons évalué trois configurations des procédures de gestion Islope, appliquées annuellement :

- Islope_10_lambda04 : $\lambda = 0,4$ et $\beta_I$ est calculé à partir des 10 années précédentes

- Islope_10_lambda08 : $\lambda = 0,8$ et $\beta_I$ est calculé à partir des 10 années précédentes

- Islope_5_lambda04 : $\lambda = 0,4$ et $\beta_I$ est calculé à partir de l’indice des cinq années précédentes

Nous avons également évalué les trois mêmes configurations, appliquées tous les cinq ans :

- Islope_10_lambda04_5u

- Islope_10_lambda08_5u

- Islope_5_lambda04_5u

Des illustrations des procédures de gestion Islope sont fournies dans @anderson2020gfmp (leur annexe D).

#### IDX : Procédure de gestion fondée sur des indices de @cox2020 {#sec:mp-idx}

Cette procédure de gestion a été utilisée dans le plan de rétablissement du sébaste aux yeux jaunes des eaux extérieures en Colombie-Britannique [@cox2020]. 
Elle attribue le TAC selon la formule suivante :

$$
\textrm{TAC}_y =
\begin{cases}
\textrm{TAC}_\textrm{Floor}, & \textrm{if}\ \Delta I_y \leq \delta_\textrm{min} \\
(1 + \Delta I_y ) \textrm{TAC}_{y-1}, & \textrm{if}\ \delta_\textrm{min} \lt \Delta I_y \leq \delta_\textrm{max} \\
(1 + \delta_\textrm{max}) \textrm{TAC}_{y-1}, & \textrm{if}\ \Delta I_y \gt \delta_\textrm{max},
\end{cases}
$$

où $\delta_\textrm{min}$ est la baisse la plus négative permise dans l’indice de la biomasse relative avant la fermeture de la pêche cette année-là et $\Delta I_y$ est défini comme suit :

$$
\Delta I_y = \frac{I_y}{I_{y-n}} - 1,
$$

où $I_y$ désigne une valeur de l’indice de la population l’année $y$ et $n$ détermine l’année de référence. 
Nous avons défini $\textrm{TAC}_\textrm{Floor} = 5 t$. 
Nous avons défini $\delta_\textrm{min} = -0,5$ comme dans @cox2020. 
L’augmentation maximale du TAC est plafonnée à $\delta_\textrm{max} = 0,25$ par défaut. 
Cela signifie que le TAC d’une année ne peut augmenter de plus de 25 %, ce qui entraîne un comportement « lent » de la procédure de gestion. 
Il serait possible de régler les paramètres $\delta_\textrm{min}$ et $\delta_\textrm{max}$ pour ajuster le comportement de la procédure de gestion.

Il est à noter que le comportement « augmentation lente--baisse rapide » déterminé par les réglages de $\delta_\textrm{min}$ et $\delta_\textrm{max}$, combiné à la variabilité simulée de l’indice du relevé, peut entraîner un « abaissement » du TAC par la procédure de gestion malgré une augmentation globale de l’indice (p. ex., figure \@ref(fig:proj-not-satisficed-eg)). 
De plus, nous avons mis en œuvre la procédure de gestion exactement comme décrit ci-dessus et dans @cox2020, qui utilise seulement $\textrm{TAC}_\textrm{Floor}$ si $\Delta I_y \leq \delta_\textrm{min}$. 
Cela n’empêche *pas* la « rampe » décrite par $(1 + \Delta I_y ) \textrm{TAC}_{y-1}$ si $\delta_\textrm{min} \lt \Delta I_y \leq \delta_\textrm{max}$ de faire lentement passer le TAC en dessous de $\textrm{TAC}_\textrm{Floor}$ (p. ex., figure \@ref(fig:proj-not-satisficed-eg)).

Cette procédure de gestion peut être lissée davantage :

$$
\textrm{TAC}_y = \lambda \cdot \textrm{TAC}_y + (1-\lambda) \textrm{TAC}_{y-1},
$$

où $\lambda$ contrôle le degré de lissage et peut varier entre 0 et 1. @cox2020 ont utilisé $\lambda=0,5$. 
Nous définissons ces procédures de gestion pour l’outil DLMtool comme "IDX" ($\delta_{\textrm{min}} = -0,5$, $\delta_{\textrm{max}} = 0,25$) et "IDX_smooth" (identique à IDX, mais avec $\lambda = 0,5$ pour répartir la différence entre le TAC proposé à venir et celui précédemment recommandé).

Nous avons évalué trois configurations des procédures de gestion IDX, appliquées chaque année :


- IDX : IDX avec $\Delta I_y = \frac{I_y}{I_{y-1}} -1$ 

- IDX_smooth : IDX_smooth avec $\Delta I_y = \frac{I_y}{I_{y-1}} -1$ 
  

- IDX_smooth_yrs5 : IDX avec $\Delta I_y = \frac{I_y}{I_{y-5}} -1$

- IDX_yrs5 : IDX_smooth avec $\Delta I_y = \frac{I_y}{I_{y-5}} -1$ 

Nous avons également évalué les quatre mêmes configurations, appliquées tous les cinq ans :

- IDX_5u

- IDX_smooth_5u

- IDX_smooth_yrs5_5u

- IDX_yrs5_5u

Des illustrations des procédures de gestion IDX sont fournies dans @anderson2020gfmp (leur annexe D).

```{r, mp-hcrs, fig.cap="Règles de contrôle des prises provisoires proposées associées aux procédures de gestion fondées sur des modèles.", fig.asp=0.38, fig.width=7.5, out.width="0.8\\textwidth"}
f <- function (Brel, LRP, TRP, rel_min = 0, rel_max = 1, ...) {
    adj <- rep(rel_max, length(Brel))
    adj[Brel <= LRP] <- rel_min
    cond <- Brel > LRP & Brel < TRP
    adj[cond] <- (rel_max - rel_min)/(TRP - LRP) * (Brel[cond] -
        LRP) + rel_min
    adj
}

pars4010 <- expand.grid(
  Brel = seq(0, 1, length.out = 200),
  LRP = c(0.1),
  TRP = c(0.4),
  type = "HCR-4010", stringsAsFactors = FALSE)
pars4010$tac <- purrr::pmap_dbl(pars4010, f)

pars8040 <- expand.grid(
  Brel = seq(0, 1, length.out = 200),
  LRP = c(0.4),
  TRP = c(0.8),
  type = "HCR-8040", stringsAsFactors = FALSE)
pars8040$tac <- purrr::pmap_dbl(pars8040, f)

parsRMD <- expand.grid(
  Brel = seq(0, 1, length.out = 200),
  LRP = NA,
  TRP = NA,
  type = "HCR-RMD", stringsAsFactors = FALSE)
parsRMD$tac <- 1

pars <- bind_rows(pars8040, pars4010) %>%
  bind_rows(parsRMD)

pars$type <- as.factor(pars$type)
pars$type <- forcats::fct_relevel(pars$type, "HCR-RMD", "HCR-4010", "HCR-8040")

make_hcr_fig <- function(dat, xlab = expression(Estimé~B/B[0])) {
  ggplot(dat, aes(Brel, tac)) +
  geom_line() +
  ggsidekick::theme_sleek() +
  labs(
    x = xlab,
    y = "Facteur d’ajustement du TAC\n(proportion de RMD"
  ) +
  geom_vline(aes(xintercept = LRP), lty = 2, alpha = 0.4) +
  geom_vline(aes(xintercept = TRP), lty = 2, alpha = 0.4)
}

g1 <- make_hcr_fig(filter(pars, type == "HCR-4010")) + ggtitle("HCR-4010")
g2 <- make_hcr_fig(filter(pars, type == "HCR-8040"), expression(Estimated~B/B[RMD])) + ggtitle("HCR-8040")

cowplot::plot_grid(g2, g1, nrow = 1)
```

