# PRÉDATION PAR LES PINNIPÈDES {#app:pinniped-predation}

En réponse aux préoccupations entourant l’augmentation des populations de phoques communs (*Phoca vitulina*), d’otaries de Steller (*Eumetopias jubatus*) et d’otaries de Californie (*Zalophus californianus*), @yamanaka2011 ont explicitement exploré l’impact potentiel de la consommation de sébastes aux yeux jaunes par les pinnipèdes dans les eaux intérieures. 
Pour ce faire, ils ont utilisé des données de recensement publiées et inédites sur les populations de pinnipèdes et des hypothèses sur leurs taux de consommation de sébastes, fondées sur les besoins bioénergétiques et les renseignements existants sur le régime alimentaire des pinnipèdes. 
La partie du régime alimentaire composée de sébastes qui est accessible pour les trois espèces de pinnipèdes a été résolue au niveau du genre (*Sebastes* spp.) parce que les fragments d’os et les otolithes récupérés à partir des échantillons de matières fécales ne peuvent être identifiés au niveau de l’espèce. 
Par conséquent, @yamanaka2011 ont supposé que la fraction de sébaste aux yeux jaunes dans l’alimentation des pinnipèdes, en pourcentage du total des *Sebastes* spp., était la même que leur occurrence moyenne dans les relevés de surveillance (relevés à la palangre, à la turlutte et au chalut), qu’ils ont calculée à 25 %. 
La même fraction a été utilisée pour les trois espèces de pinnipèdes, bien que l’écologie des phoques communs, des otaries de Californie et des otaries de Steller diffère considérablement, tout comme leur poids maximal : 80 kg, 390 kg et 1 100 kg, respectivement [@ford2014].

Comparativement à d’autres sébastes courants dans le détroit de Georgie, comme le sébaste à queue jaune, le sébaste cuivré et les sébastes de la baie Puget, le sébaste aux yeux jaunes est plus gros et vit dans de plus grandes profondeurs. De ce fait, le sébaste aux yeux jaunes est moins susceptible d’être consommé par de plus petits prédateurs comme le phoque commun et l’otarie de Californie. 
De plus, les otaries de Steller, les épaulards (*Orcinus orca*) et le saumon chinook (*Oncorhynchus tshawytscha*) sont les seuls prédateurs du sébaste aux yeux jaunes figurant dans une grande base de données sur les interactions prédateur-proie (base de données assemblée pour @dunne2016; @szoboszlai2015). 
Des chercheurs du MPO qui travaillent sur les pinnipèdes ont entrepris un important programme de relevés pour identifier leurs proies par espèce, en recourant à l’analyse génétique d’échantillons d’excréments. 
Les résultats préliminaires n’ont pas permis de déterminer la présence de sébaste aux yeux jaunes dans les excréments des phoques communs (n = 1 248) ou des otaries de Californie (n = 116). Selon ces mêmes résultats, le sébaste aux yeux jaunes constitue 0,1 % du régime alimentaire des otaries de Steller dans le détroit de Georgie (n = 331) et sur la côte ouest de l’île de Vancouver (n = 340) [S. Tucker, Sciences du MPO, données inédites]. 
Il convient de noter que la portée temporelle et spatiale de cette analyse est limitée et que la taille des échantillons pour les données qui ont été analysées à ce jour est relativement petite. 
En outre, les données préliminaires accessibles sont le pourcentage des lectures d’ADN des espèces par rapport aux lectures d’ADN total et ne sont pas encore étalonnées en termes de rendements de biomasse pour corriger les biais méthodologiques et biologiques (S. Tucker, Sciences du MPO, comm. pers., 7 avril 2020).   

Les populations d’otaries de Steller ont connu de graves déclins en Colombie-Britannique en raison de la chasse et de l’abattage dirigé de prédateurs, qui étaient en place de 1912 à 1968, mais leur abondance a commencé à augmenter après la protection instaurée en 1970 [@ford2014; @olesiuk2018]. Le sébaste aux yeux jaunes des eaux intérieures est plus exposé au risque de prédation par les otaries de Steller l’hiver, celles-ci se regroupant dans les roqueries de reproduction le long de la côte extérieure pendant l’été, bien qu’on ait récemment observé un petit nombre d’animaux (~500) toute l’année dans le détroit de Georgie.^[Majewski, S., Szaniszlo, W., Nordstrom, C.A., Abernethy, R.M., and Tucker, S. 2020. Trends in abundance of Steller Sea Lions Eumetopias jubatus in British Columbia: Updates from 2016--17 aerial surveys. DFO Can. Sci. Advis. Sec. Res. Doc. En préparation.]
Les estimations de la population hivernale des otaries sont moins fiables que celles de l’été, car les animaux passent plus de temps dans l’eau qu’échoués sur terre et sont plus dispersés, ce qui les rend plus difficiles à dénombrer. 
L’abondance de l’otarie de Steller en Colombie-Britannique est environ 1,25 fois plus élevée en hiver, car les animaux des territoires adjacents hivernent dans les eaux de la Colombie-Britannique [@olesiuk2018]. 
@yamanaka2011 ont constaté que la proportion d’otaries de Steller hivernant dans les eaux intérieures était assez constante au fil du temps, à 4,8 % des dénombrements hivernaux dans le sud de la Colombie-Britannique. 
En utilisant cette proportion, ils ont estimé que le nombre d’otaries de Steller dans la zone 4B avait diminué jusqu’à un creux d’environ 500 animaux en 1970, puis avait augmenté pour retrouver approximativement l’abondance enregistrée au début de la série chronologique en 1913 (1 897 en 1913, contre 1 837 en 2010). 
Depuis 2010, le nombre d’otaries de Steller en Colombie-Britannique a continué d’augmenter [@olesiuk2018]; toutefois, l’abondance estimée du relevé de 2017 se situe dans l’intervalle de confiance de l’estimation de 2013.  

Les taux de mortalité du sébaste aux yeux jaunes résultant de la prédation par l’otarie de Steller étaient probablement plus bas dans la deuxième moitié des années 1900 (1959 et 1999), lorsqu’on estimait que moins de 1 000 animaux étaient présents dans les eaux intérieures (données présentées dans les tableaux F4 et F5 de @yamanaka2011), et ils ont sans doute augmenté avec le rétablissement de la population d’otarie de Steller à un niveau semblable ou supérieur à celui du début des années 1900.
D’autres études sur la prédation du sébaste aux yeux jaunes par l’otarie de Steller dans l’espace et dans le temps seraient utiles pour affiner les estimations de la mortalité, tout comme des méthodes pour intégrer la mortalité variable dans le temps. 
