---
title: "Évaluation des stratégies de rétablissement possibles pour le sébaste aux yeux jaunes (*Sebastes ruberrimus*) des eaux intérieures de la Colombie-Britannique"
author: |
  Dana R. Haggarty^1^,
  Quang C. Huynh^2^,
  Robyn E. Forrest^1^,
  Sean C. Anderson^1^,
  Midoli J. Bresch^1^,
  Elise A. Keppel^1^
  
author_list: "Haggarty, D.R., C.R. Huynh, R.E. Forrest, S.C. Anderson, M.J. Bresch, et E.A. Keppel"
address: |
    ^1^Station biologique du Pacifique\
      Pêches et Océans Canada, 3190, chemin Hammond Bay\
      Nanaimo (Colombie-Britannique) V9T 6N7, Canada\
      
    ^2^Institut pour les océans et la pêche\
     LRAE de l’Université de la Colombie- Britannique, 2202, Main Mall\
     Vancouver (Colombie-Britannique)  V6T 1Z4, Canada\
citation_other_language: "Haggarty, D.R., Huynh, Q.C., Forrest, R.E., Anderson, S.C., Bresch, M.J., Keppel, E.A. 2021. Evaluation of potential rebuilding strategies for Inside Yelloweye Rockfish (*Sebastes ruberrimus*) in British Columbia. DFO Can. Sci. Advis. Sec. Res. Doc. 2021/008. vi + 141 p."
year: 2021
report_number: 008
isbn: "Fs70-5/2021-008F-PDF"
cat_no: "978-0-660-38699-7"
region: Pacific Region
copy_sty: false


abstract: |
  En vertu des politiques et de la législation canadiennes, il faut Eétablir un plan de rétablissement pour les stocks de poissons qui ont été évalués comme étant inférieurs au point de référence limite (PRL) afin de les ramener au-delà du PRL. Les plans de rétablissement doivent être fondés sur des objectifs caractérisés par 1) une cible, 2) un délai souhaité pour atteindre la cible et 3) une probabilité acceptable d’atteindre la cible. Les plans de rétablissement doivent également comprendre des mesures de gestion ou des procédures de gestion, des jalons cibles et être évalués régulièrement.
  
  Le stock de sébaste aux yeux jaunes (*Sebastes ruberrimus*) des eaux intérieures est un stock sur lequel on dispose de données limitées, présent dans la zone de gestion du poisson de fond 4B (détroit de la Reine-Charlotte, détroit de Georgie et détroit de Juan de Fuca) en Colombie-Britannique. Il a été évalué comme étant inférieur au PLR en 2010, ce qui a donné lieu à la publication d’un plan de rétablissement. Il est également inscrit en vertu de la *Loi sur les espèces en péril* comme espèce préoccupante. L’actuelle procédure de gestion pour assurer le rétablissement est un total autorisé des captures (TAC) annuel fixe de 15 tonnes métriques, qui n’a pas été réévalué depuis la dernière évaluation.
  
   Ce projet vise à fournir un avis scientifique à l’appui de la réévaluation du plan de rétablissement du sébaste aux yeux jaunes des eaux intérieures. Nous appliquons un nouveau cadre d’évaluation de la stratégie de gestion (le Cadre des procédures de gestion), récemment élaboré pour le poisson de fond de la Colombie-Britannique, afin d’évaluer le rendement des autres procédures de gestion à données limitées pour ce qui est de l’atteinte des objectifs de rétablissement. Le Cadre des procédures de gestion suit six étapes de pratiques exemplaires pour évaluer la stratégie de gestion : 1) la définition du contexte décisionnel; 2) l’établissement des objectifs et des paramètres de rendement; 3) la précision des modèles opérationnels pour représenter le système sous-jacent et calculer les paramètres de rendement; 4) la sélection des procédures de gestion possibles; 5) la réalisation de simulations en boucle fermée afin d’évaluer le rendement des procédures de gestion; 6) la présentation des résultats pour faciliter l’évaluation des compromis.
 
   Nous avons appliqué ce cadre pour évaluer le rendement de 34 procédures de gestion à données limitées pour ce qui est de l’atteinte de l’objectif principal, qui est de ramener le stock au-dessus du PRL sur 1,5 génération avec au moins une probabilité de réussite de 95 % [19 fois sur 20]. Nous avons également évalué le rendement des procédures de gestion en ce qui concerne deux autres paramètres de conservation, quatre objectifs de prises moyennes et un objectif de variabilité des prises. Pour tenir compte de l’incertitude liée à la dynamique de la population sous-jacente et aux sources de données, nous avons élaboré six scénarios de modèles opérationnels de rechange, qui différaient de par les hypothèses précises du modèle et des données. Ces scénarios de modèles opérationnels ont été divisés en un « ensemble de référence » (quatre modèles opérationnels) et un « ensemble de robustesse » (deux modèles opérationnels). Nous avons conditionné tous les modèles opérationnels aux données sur les prises observées, aux indices de l’abondance et aux données accessibles sur la composition selon l’âge. Nous avons utilisé la simulation en boucle fermée pour évaluer le rendement des procédures de gestion et nous avons éliminé celles qui ne satisfaisaient pas à un ensemble de critères de base, ce qui a laissé cinq procédures de gestion possibles : des procédures de gestion à prises constantes annuelles de 10 ou 15 tonnes et trois procédures de gestion qui ajustent le TAC en fonction de la pente relative de l’indice de l’abondance dans le relevé à la palangre sur fond dur dans les eaux intérieures.
 
  Les cinq procédures de gestion finales atteignaient l’objectif principal avec une probabilité supérieure à 0,98 (49 fois sur 50), dans les scénarios des quatre modèles opérationnels de l’ensemble de référence, surtout qu’aucun des modèles opérationnels de l’ensemble de référence n’a estimé que le stock serait inférieur au PRL en 2020. Dans les scénarios des deux modèles opérationnels de l’ensemble de robustesse, le scénario qui simulait une plus grande variabilité dans le futur relevé à la palangre sur fond dur a donné des résultats semblables à ceux des scénarios de l’ensemble de référence. Cependant, dans le scénario qui supposait un taux de mortalité naturelle plus faible pour le stock (« M faible »), toutes les procédures de gestion avaient des probabilités plus basses d’atteindre l’objectif principal, la probabilité la plus faible étant atteinte par la procédure de gestion actuelle (prises constantes de 15 tonnes).
 
  Nous présentons un certain nombre de visualisations pour illustrer les compromis entre les objectifs de conservation et de prises pour les différentes procédures de gestion dans d’autres scénarios de modèles opérationnels. Ces visualisations présentent les compromis sous forme de tableaux et de graphiques, destinés à faciliter le processus de sélection de la procédure de gestion finale. Étant donné que toutes les procédures de gestion ont atteint l’objectif principal dans les scénarios de l’ensemble de référence, il n’y avait pas de compromis important entre les objectifs de conservation et les objectifs de prises. Parmi les deux scénarios de l’ensemble de robustesse, les compromis étaient les plus évidents dans le scénario de M faible, où la probabilité d’atteindre l’objectif principal diminuait à mesure que la probabilité de prises moyennes à court terme de 10 tonnes augmentait.
 
  Nous discutons des incertitudes majeures, y compris l’incertitude entourant la mortalité naturelle, la sélectivité et les prises historiques, en notant que nous avons tenté d’en tenir compte en évaluant le rendement des procédures de gestion dans plusieurs modèles opérationnels. Nous soulignons les problèmes concernant les estimations de l’état actuel du stock de sébaste aux yeux jaunes des eaux intérieures et le rôle des points de référence dans le Cadre des procédures de gestion. Nous formulons des recommandations sur la fréquence des évaluations et suggérons des déclencheurs pour la réévaluation. Nous évaluons également le rendement des procédures de gestion en ce qui concerne le respect de deux autres critères d’évaluation pour le Comité sur la situation des espèces en péril au Canada.

# header: "Draft working paper --- Do not cite or circulate" # or "" to omit
output:
 csasdown::resdoc_pdf:
   french: true
  # csasdown::resdoc_word
# ------------
# End of options to set
knit: bookdown::render_book
link-citations: true
bibliography: [refs.bib, mpframework-refs.bib]
csl: csl/csas-french.csl # or csl/csas-french.csl for French
# Any extra LaTeX code for the header:
# header-includes:
# - \usepackage{etex}

---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 7.5
fig_out_width <- "5.5in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  autodep = TRUE,
  cache = FALSE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)
options(french = TRUE)
```

```{r load-libraries, cache=FALSE}
library(gfutilities)
library(csasdown)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(rosettafish)
library(here)
filter <- dplyr::filter
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(crop = NULL)
round2 <- function(x, never_perfect = TRUE) {
  out <- sprintf("%.2f",round(x, 2))
  if (out == "1.00" && never_perfect)
    out <- "> 0.99"
  if (out == "0.00" && never_perfect)
    out <- "< 0.01"
  out
}


csl <- "csl/csas-french.csl"
options(OutDec =  ",")
options(tinytex.verbose = TRUE)
```

